cli-tools/bin/code_signing_manager.rb

Fixes
```
cli-tools/bin/code_signing_manager.rb:135:in `resolve_from_target_or_config': undefined local variable or method `build_configuration' for #<VariableResolver:0x00007fd87e04cde8> (NameError)
from cli-tools/bin/code_signing_manager.rb:63:in `block in resolve'
from cli-tools/bin/code_signing_manager.rb:62:in `each'
from cli-tools/bin/code_signing_manager.rb:62:in `resolve'
from cli-tools/bin/code_signing_manager.rb:299:in `get_bundle_id'
from cli-tools/bin/code_signing_manager.rb:404:in `set_configuration_build_settings'
from cli-tools/bin/code_signing_manager.rb:458:in `block in set_target_build_settings'
from cli-tools/bin/code_signing_manager.rb:457:in `each'
from cli-tools/bin/code_signing_manager.rb:457:in `set_target_build_settings'
from …
```

Fix NameError in resolve_from_target_or_config

---

cli-tools/bin/code_signing_manager.rb

Fixes
```ruby
cli-tools/bin/code_signing_manager.rb:112:in `block in resolve_variable_from_target_configs': undefined local variable or method `key' for #<VariableResolver:0x00007fe67d316238> (NameError)
cli-tools/bin/code_signing_manager.rb:108:in `each'
cli-tools/bin/code_signing_manager.rb:108:in `resolve_variable_from_target_configs'
cli-tools/bin/code_signing_manager.rb:137:in `resolve_from_target_or_config'
cli-tools/bin/code_signing_manager.rb:63:in `block in resolve'
cli-tools/bin/code_signing_manager.rb:62:in `each'
cli-tools/bin/code_signing_manager.rb:62:in `resolve'
cli-tools/bin/code_signing_manager.rb:299:in `get_bundle_id'
cli-tools/bin/code_signing_manager.rb:404:in `set_configuration_build_settings'
cli-tools/bin/code_signing_manager.rb:458:in `block in …
```

Fix NameErrors in code signing manager

---

codemagic.yaml
setup.py
src/codemagic_cli_tools/cli/cli_app.py
src/codemagic_cli_tools/cli/cli_types.py
src/codemagic_cli_tools/git_changelog.py

Code you return to `__main__` will be interpreted as system exit code. Change cli app invocation logic to take that into account. Return code `0` by default unless an error is catched, then return an other error code, instead of running `sys.exit()` manually.
Also send exit code 1 from empty git log and skip the newline.

Do not exit with code 1 when action returns something

---

src/codemagic/__version__.py
src/codemagic/models/xcodebuild.py

Capturing unprocessed `xcodebuild` log into log file was not working properly and the tail of the actual log was not always included.

Bugfix: Fix Xcode log copying

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/provisioning_profile.py
tests/models/test_provisioning_profile.py

If provisioning profile does not contain key `IsXcodeManaged`, then a fallback detection is initiated that checks if the provisioning profile name suggests that it is Xcode managed. Up until now the App Store and Ad Hoc profiles were always treated as _not_ managed by Xcode, in case they were lacking the `IsXcodeManaged` key.

Bugfix: Xcode managed profiles

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/resource_printer.py

Enums and other non-string objects cannot be escaped directly with `shlex.quote`. This caused the tool to crash:
```python
File "/usr/local/lib/python3.7/site-packages/codemagic/cli/cli_app.py", line 149, in invoke_cli
app._invoke_action(args)
File "/usr/local/lib/python3.7/site-packages/codemagic/cli/cli_app.py", line 132, in _invoke_action
File "/usr/local/lib/python3.7/site-packages/codemagic/cli/cli_app.py", line 323, in wrapper
File "/usr/local/lib/python3.7/site-packages/codemagic/tools/app_store_connect.py", line 493, in fetch_signing_files
profile_type, certificate_key, certificate_key_password, create_resource)
File "/usr/local/lib/python3.7/site-packages/codemagic/tools/app_store_conn …
```

Bugfix: Handle non string objects when logging Apple Developer Portal resource creation

---

CHANGELOG.md
docs/app-store-connect/create‑bundle‑id.md
docs/app-store-connect/fetch‑signing‑files.md
docs/app-store-connect/list‑bundle‑ids.md
docs/app-store-connect/list‑devices.md
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/provisioning/profiles.py
src/codemagic/apple/resources/enums.py
src/codemagic/tools/app_store_connect.py
tests/apple/app_store_connect/provisioning/conftest.py
tests/apple/app_store_connect/provisioning/test_profiles.py

Attaching devices to App Store and In House provisioning profiles is not valid. Example log of failing request:
```
[04:43:07 12-03-2020] INFO  resource_printer.py:72 > Creating new Profile: name: '...', profile type: IOS_APP_STORE, bundle id: ..., certificates: ['...']
[04:43:07 12-03-2020] INFO  api_session.py:31 > >>> POST https://api.appstoreconnect.apple.com/v1/profiles None
[04:43:07 12-03-2020] INFO  api_session.py:21 > <<< 409 {'errors': [{'id': '9f2d1584-d967-4d2b-9a3b-a824afc95e3f', 'status': '409', 'code': 'ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED', 'title': 'A relationship in the provided entity is not allowed for this request', 'detail': 'No devices can be associated to Provisioning Profiles for the App Store.'}]}
[04:43:07 12-03-2020] ERROR cli_app.py:107 >  POST …
```

Bugfix: Creating iOS App Store and In House provisioning profiles

---

CHANGELOG.md
Pipfile.lock
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/api_client.py

When paginating resources in Apple Developer Portal, the URL parameters from previous API calls are urlencoded into the next URL. Thus we end up sending duplicate URL parameters when paginating.
For example, when listing Bundle IDs, then the first request is
```javascript
>>> GET https://api.appstoreconnect.apple.com/v1/bundleIds {'limit': 20, 'sort': 'name'}
<<< 200 {
"data": [],
"links": {
"self": "https://api.appstoreconnect.apple.com/v1/bundleIds?sort=name&limit=20",
"next": "https://api.appstoreconnect.apple.com/v1/bundleIds?sort=name&cursor=eyJvZmZzZXQiOiIyMCJ9&limit=20"
},
"meta": {
"paging": {
"total": 21,
"limit": 20
}
}
}
```
It is followed by this failing request:
```javascript
>>> GET https://api.appstoreconnect.apple.com/v1/bundleIds?sort=name&cursor=eyJvZmZzZXQiOiIyMCJ9&limit …
```

Bugfix: Apple Developer Portal pagination

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/argument.py
tests/tools/test_app_store_connect.py

When instead of CLI arguments envrionemnt variables are used to define the argument values then on invalid input values the command execution fails unexpectely with vague error messages.
Take for example `APP_STORE_CONNECT_PRIVATE_KEY="..."` environment variable in place of `--private-key="..."` as described in the [docs](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/README.md#--private-keyprivate_key)) for `app-store-connect`.
Previously the result with value from environment variable was like
```bash
$ APP_STORE_CONNECT_PRIVATE_KEY="not a valid private key" app-store-connect fetch-signing-files io.bundleId.example
Executing AppStoreConnect action fetch-signing-files failed unexpectedly. Detailed logs are available at …
```

Improve error message for invalid user input

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/cli_process.py

Running
```{shell}
android-app-bundle is-signed --bundle /path/to/bundle.aab
```
did not return in case of some Android app bundles as reading `stderr` stream halted. Mitigate this by adding graceful timeouts to reading from child processes.

Bugfix: Checking if Android app bundle is signed got stuck

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/cli_process.py
tests/cli/test_cli_process.py

Streams on `Popen` objects are `None` if the streams are initialized as file descriptors. That resulted with
```{python}
AttributeError: 'NoneType' object has no attribute 'fileno'
```

Bugfix: Process stream descriptor nullpointer

---

CHANGELOG.md
bin/code_signing_manager.rb
src/codemagic/__version__.py

In some cases setting code signing settings failed since the resolved variable actually contained the key that was being resolved. For example bundle ID
```
'${PRODUCT_BUNDLE_IDENTIFIER}.OneSignalNotificationServiceExtension'
```
was resolved to
```
${PRODUCT_BUNDLE_IDENTIFIER}.OneSignalNotificationServiceExtension.OneSignalNotificationServiceExtension
```
because `PRODUCT_BUNDLE_IDENTIFIER` was expanded to 
```
${PRODUCT_BUNDLE_IDENTIFIER}.OneSignalNotificationServiceExtension.OneSignalNotificationServiceExtension
```
This of course is not a desired result and we should discard the recursive definitions when looking up the final value.

Bugfix: Improve variable resolving from Xcode projects

---

CHANGELOG.md
docs/xcode-project/build-ipa.md
src/codemagic/__version__.py
src/codemagic/models/xcodebuild.py
src/codemagic/tools/xcode_project.py

**Changes**:
- Add option to define where the `xcarchive` package is saved during `build-ipa` execution. It now defaults to `build/ios/xcarchive` whereas it used to be in `$TMPDIR`.
- Always log out the exact `xcodebuild` commands that are being executed for transparency, even without verbose mode.

Feature: Add option to specify where intermediate xcarchive is stored for `xcode-project build-ios`

---

CHANGELOG.md
bin/code_signing_manager.rb
src/codemagic/__version__.py

In case build configuration is missing base configuration reference we failed to obtain bundle ID for this build configuration. To overcome this, check root project build configurations and check if there are build settings for this configuration. If so, check the `PRODUCT_BUNDLE_IDENTIFIER` value from there.

Improvement: Attempt to parse product bundle identifier from root project

---

CHANGELOG.md
docs/app-store-connect/list-bundle-id-profiles.md
docs/app-store-connect/list-profiles.md
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py

Despite the supported states `ACTIVE` and `INVALID` defined in the Profile resource API [documentation](https://developer.apple.com/documentation/appstoreconnectapi/profile/attributes), for some cases the API responds with `profileState` attribute set to `EXPIRED`.
For example the profile entry in the response of `GET https://api.appstoreconnect.apple.com/v1/bundleIds/<bundle_id_resource_id>/profiles` was
```javascript
{
"type": "profiles",
"id": "<profile_resource_id>",
"attributes": {
"profileState": "EXPIRED",   // <-- this should not happen according to the docs
"createdDate": null,
"profileType": "IOS_APP_STORE",
"name": "iOS Team Store Provisioning Profile: com.example.app",
"profileContent": "...",
"uuid": "d0e231cf-2d40-4c68-af54-8df241acb71a",
"platform": "IOS",
"expirationDate": …
```

Bugfix: Support profile state 'EXPIRED'

---

CHANGELOG.md
docs/xcode-project/build-ipa.md
src/codemagic/__version__.py
src/codemagic/tools/xcode_project.py

When building ipa using `xcode-project build-ipa` the intermediate `xcarchive` container was always removed. But often times we'd like to persist the archive too. Change the default behaviour so that the xcarchive is removed only if `--remove-xcarchive` feature flag is specified.

Feature: Optional xcarchive removal

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/code_sign_entitlements.py
src/codemagic/tools/xcode_project.py
tests/models/mocks/mock_0_icloud_container_environments.plist
tests/models/mocks/mock_1_icloud_container_environments.plist
tests/models/mocks/mock_2_icloud_container_environments.plist
tests/models/test_code_sign_entitlements.py

Entitlements in xcarchvies can specify all possible values for iCloudContainerEnvironment. Choose the most sensible for exporting ipa.

Bugfix: Support choosing iCloudContainerEnvironment from multiple options

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/xcode_project.py

If given export options plist does not exist then running `xcode-project build-ipa` action fails unexpectely:
```bash
$ xcode-project build-ipa --project Project.xcodeproj --export-options-plist missing-export-options.plist
Executing XcodeProject action build-ipa failed unexpectedly. Detailed logs are available at "/var/folders/s_/1kqm5m1x0gg_r7yvbm2j1h3h0000gn/T/codemagic-11-09-20.log". To see more details about the error, add `--verbose` command line option.
```
With the introduced changes the reason for error is highlighted in a more user-friendly fashion:
```bash
$ xcode-project build-ipa --project Project.xcodeproj --export-options-plist missing-export-options.plist
usage: xcode_project.py [-h] [--log-stream {stderr,stdout}] [--no-color] [--version] [-s] [-v] …
```

Improvement: Improv error handling for missing export options on build-ipa

---

CHANGELOG.md
docs/xcode-project/build-ipa.md
src/codemagic/__version__.py
src/codemagic/models/xcodebuild.py
src/codemagic/tools/xcode_project.py

Resolves PR https://github.com/codemagic-ci-cd/cli-tools/issues/27.
**New feature**:
Add option to specify custom `xcodebuild` arguments and flags for `archive` and `-exportArchive` actions that are launched as part of `xcode-project build-ipa` using the following modifiers:
- `--archive-flags`,
- `--archive-xcargs`,
- `--export-flags` and
- `--export-xcargs`.

Feature: Custom xcodebuild flags and options

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/keychain.py

It used to be that `keychain add-certificate` would exit with status code 1 in case a certificate that already exists in specified keychin exists. Like that:
```bash
> keychain add-certificates
Add certificates to keychain /Users/priit/Library/Keychains/login.keychain-db
Searching for files matching /Users/priit/Library/MobileDevice/Certificates/*.p12
Add certificate /Users/priit/Library/MobileDevice/Certificates/IOS_DEVELOPMENT_certificate_3924A8A5ADAD4FBE_jsq0iv3p.p12 to keychain /Users/priit/Library/Keychains/login.keychain-db
1 key imported.
1 certificate imported.
Add certificate /Users/priit/Library/MobileDevice/Certificates/IOS_DEVELOPMENT_certificate_3924A8A5ADAD4FBE_w7m2zrrp.p12 to keychain /Users/priit/Library/Keychains/login.keychain-db
security: SecKeychainItemImport: The …
```

Bugfix: Do not fail `keychain add-certificate` if certificate already exists in keychain 

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/xcodebuild.py
src/codemagic/models/xcpretty.py

Use single Xcpretty process thoughout the xcodebuild invokation to format logs instead of creating separate process to format each chunk.

Improvement: Single Xcpretty process to format xcodebuild logs

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/cli_process.py
src/codemagic/models/xcodebuild.py

Currently `xcode-project` stores `xcodebuild` logs both in memory and in a file. The former is not needed and adds unnecessary memory overhead.

Improvement: Do not store xcodebuild logs in memory

---

CHANGELOG.md
doc.py
docs/keychain/add-certificates.md
src/codemagic/__version__.py
src/codemagic/cli/argument/argument.py
src/codemagic/tools/keychain.py
tests/tools/test_keychain.py

**Add options to `keychain add-certificates` to specify which applications have access to the imported certificate without warning.**
Up until now certificates are added to specified keychain in a way that only `codesign` can access them without prompting UI warning. But to fulfill the needs for not only iOS developers it might be necessare to make certificates usable from headless session for other executables too, such as `productsign`, which is used to sign macOS applications. The apps that can access certificate in keychain can be configured during import via `-T` flag on `security import ...`. If one desires to make the certificate fully available for all applications without warning, then it can be imported to keychain using `security import` in conjunction with`-A` option. By …

Improvement: Add option to specify allowed apps for keychain add-certificates

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/provisioning/bundle_ids.py
tests/apple/app_store_connect/provisioning/test_bundle_ids.py

App Store Connect's [List Bundle IDs](https://developer.apple.com/documentation/appstoreconnectapi/list_bundle_ids) API endpoint does not respect the value of `filter[platform]` query parameter and always returns bundle identifiers for all platforms. This leads to unexpected consequences and as such we need to do client side filtering in order to avoid this.

Bugfix: Fix platform filter for listing bundle identifiers from App Store Connect

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
tests/apple/resources/enums/test_profile_type.py

Only development and ad hoc provisioning profiles allow specifying concrete devices in them, and as such previous implementation had flaws in it since only profiles with types `IOS_APP_STORE` and `IOS_APP_INHOUSE` excluded device listings.
This lead to `409` responses from [App Store Connect API Create Profile](https://developer.apple.com/documentation/appstoreconnectapi/create_a_profile) endpoint. For example:
```python
[08:48:05 02-03-2021] INFO  resource_printer.py:72 > Creating new Profile: name: 'profile name', profile type: TVOS_APP_STORE, bundle id: 1IAVWZM6EV, certificates: ['13CO2HS7YE']
[08:48:05 02-03-2021] INFO  api_session.py:32 > >>> POST https://api.appstoreconnect.apple.com/v1/profiles {
"data": {
"type": "profiles",
"attributes": {
"name": "profile name",
"profileType": …
```

Bugfix: Create provisioning profile fails for some profile types due to included devices

---

CHANGELOG.md
docs/xcode-project/use-profiles.md
src/codemagic/__version__.py
src/codemagic/tools/_xcode_project/arguments.py
src/codemagic/tools/xcode_project.py

Use case is when some `node_modules` or other dependency has an xcode project which can't be signed.
In such case instead of specifying the exact project, user can use the `--warn-only` flag.
Not outputting the exception to warning since it's quite long.

Allow to not fail the `use-profiles` action when profile(s) can't be applied to a project(s)

---

doc.py
setup.cfg
src/codemagic/cli/__init__.py
src/codemagic/cli/action_group.py
src/codemagic/cli/argument/action_callable.py
src/codemagic/cli/cli_app.py

Currently each tool has a flat actions structure, which means that only invocations such as
```bash
app-store-connect action-a <action args>
app-store-connect action-b <action args>
```
are possible, but it would be nice to have option to group commands into categories and interact with them by subcommands such as
```bash
app-store-connect action-group-a subaction-a <action args>
app-store-connect action-group-a subaction-b <action args>
app-store-connect action-group-b subaction-a <action args>
app-store-connect action-group-c subaction-c <action args>
```
This comes in handy since tools such as [app-store-connect](https://github.com/codemagic-ci-cd/cli-tools/tree/v0.5.2/docs/app-store-connect) are already getting rather cluttered by current flat approach and there are more actions …

Add option to group CLI actions into groups

---

CHANGELOG.md
Pipfile
Pipfile.lock
setup.py
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/api_client.py

[PyJWT](https://pyjwt.readthedocs.io/en/stable/) version 2.0.0 introduced tiny change in the API that `jwt.encode` started returning `str` instead of `bytes` as in earlier versions. This caused a regression that was fixed in [v0.4.2](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.4.2) by freezing PyJWT version to 1.7.1.
To be compatible with the API change, handle both `str` and `bytes` type tokens in App Store Connect API client for backwards compatibility. But not to lag behind with outdated dependencies, bump PyJWT dependency to 2.0.0+ in requirements.

Dependencies: Use PyJWT 2.0.1

---

CHANGELOG.md
docs/app-store-connect/fetch-signing-files.md
docs/app-store-connect/list-bundle-ids.md
docs/xcode-project/use-profiles.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/app_store_connect.py

**Closes #63**
Define new option `--strict-match-identifier` for `app-store-connect` actions `fetch-signing-files` and `list-bundle-ids` to include only those bundle IDs whose identifier strictly matches given input.
**Example usage:**
- Without strictly matching
```bash
> app-store-connect list-bundle-ids --bundle-id-identifier io.codemagic.banaan
Found 2 Bundle IDs matching specified filters: identifier=io.codemagic.banaan.
-- Bundle ID --
Id: NLRN94JD59
Type: bundleIds
Identifier: io.codemagic.banaan
Name: banaan
Platform: IOS
Seed id: X8NNQ9CYL2
-- Bundle ID --
Id: R4FZDMGMBR
Type: bundleIds
Identifier: io.codemagic.banaan.Clip
Name: io codemagic banaan Clip
Platform: UNIVERSAL
Seed id: X8NNQ9CYL2
```
- With strict modifier
```bash
> app-store-connect list-bundle-ids …
```

Feature: Add option to strictly match bundle ID identifier for app-store-connect actions

---

CHANGELOG.md
docs/app-store-connect/get-latest-app-store-build-number.md
docs/app-store-connect/get-latest-testflight-build-number.md
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/versioning/app_store_versions.py
src/codemagic/apple/app_store_connect/versioning/pre_release_versions.py
src/codemagic/apple/resources/app_store_version.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/app_store_connect.py

In case several projects (for iOS, macOS, tvOS) are under the same application ID, then `app-store-connect` actions
- `get-latest-testflight-build-number`
- `get-latest-app-store-build-number`
fail to deliver the the expected result as you could need macOS version, but are returned iOS version instead. 
To deal with this issue, add `--platform` option to those actions to specif for which platform you want to obtain the version for.

Feature: Add option to filter builds with app-store-connect by platform

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
src/codemagic/apple/resources/profile.py
src/codemagic/tools/app_store_connect.py

macOS related profiles should be exported with `.provisionprofile` extension, not `.mobileprovision`.
When trying to use `.mobileprovision` profile on macOS the next error is encountered:
```
DVTProvisioningProfileManager: Failed to load profile "/Users/builder/Library/MobileDevice/Provisioning Profiles/6FE7F7F2-8D73-4800-9AC6-060836455F5D.mobileprovision" (Error Domain=DVTProvisioningProfileProviderErrorDomain Code=2 "Failed to load profile data." UserInfo={NSLocalizedDescription=Failed to load profile data., NSLocalizedRecoverySuggestion=Profile "macos desktop distribution" (07b29e64-4690-4180-aecd-777cdeaa49db) has unsupported platforms "macOS". Profiles with the "mobileprovision" file extension should have one of "tvOS", "watchOS", or "iOS".})
```
Example of usage (correct profile …

Fix macos profiles extension

---

CHANGELOG.md
bin/code_signing_manager.rb
codemagic.yaml
src/codemagic/__version__.py
src/codemagic/models/certificate.py
src/codemagic/models/provisioning_profile.py
src/codemagic/tools/_xcode_project/arguments.py
src/codemagic/tools/xcode_project.py
tests/models/test_certificate.py

Changes required to be able to sign macOS apps:
1) list MacOS application's codesigning certificates as well in `keychain list-certificates`.
Mainly need to be used inside `xcode-project use-profiles`. So include `Developer ID`, `Mac Developer` and `3rd party Mac Developer Application/Installer` certificates.
2) in `xcode-project use-profiles` search for provision profiles with `.provisionprofile` extension as well.
add a second default path.
3) handle provisioning profiles entitlements keys with prefixes e.g. `com.apple.application-identifier`
macos profiles contain entitlements with `com.apple` prefix, need to handle it. Not sure it's the case with `beta-reports-active` as I didn't see it, but let's just have it.
```bash
<key>Entitlements</key>
<dict> …
```

Macos signing improvements

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/google_play/resources/track.py
tests/google_play/resources/test_resource_print.py

A draft release without name set and without uploaded binaries won't have name. So need to set `name` as an optional field.
Tested, it's fine.
```bash
> google-play get-latest-build-number --package-name <app_id> -v --log-api-calls --json
[14:47:30] INFO  > Create an edit for the package "<app_id>"
[14:47:31] INFO  > {
"id": "13756145079442875546",
"expiryTimeSeconds": "1619099251"
}
[14:47:31] INFO  > Get information about the track "internal" for the package "<app_id>"
[14:47:32] INFO  > {
"track": "internal",
"releases": [
{
"status": "draft"
},
{
"status": "completed",
"name": "201 (1.9.1)",
"versionCodes": [
"201"
],
"releaseNotes": [
{
"language": "en-US",
"text": "<app_id>"
}
]
}
]
}
[14:47:32] INFO  > Latest version code for internal track: 201
[14:47:32] INFO  > Get information …
```

Fix google failure failure when no release name provided

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py

Responses to `GET https://api.appstoreconnect.apple.com/v1/bundleIds` include Bundle Identifiers whose platform is `SERVICES`:
```
{
"type": "bundleIds",
"id": "...",
"attributes": {
"name": "Sign in with Apple",
"identifier": "...",
"platform": "SERVICES",
"seedId": "..."
},
"relationships": {
...
},
"links": {
...
}
}
```
Such a value causes `ValueError` on model initializations:
```python
File "/usr/local/lib/python3.8/site-packages/codemagic/apple/app_store_connect/provisioning/bundle_ids.py", line 104, in list
return [bundle_id for bundle_id in bundle_ids if resource_filter.matches(bundle_id)]
File "/usr/local/lib/python3.8/site-packages/codemagic/apple/app_store_connect/provisioning/bundle_ids.py", line 104, in <listcomp>
return [bundle_id for …
```

Bugfix: Include 'SERVICES' to BundleIdPlatform enum

---

CHANGELOG.md
docs/app-store-connect/create-bundle-id.md
docs/app-store-connect/fetch-signing-files.md
docs/app-store-connect/get-profile.md
docs/app-store-connect/list-bundle-ids.md
docs/app-store-connect/list-devices.md
docs/xcode-project/use-profiles.md
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py

Add action to get single provisioning profile information using `app-store-connect`.
**New actions:**
- `app-store-connect get-profile`
**Example executions of new actions**
- Get profile information by resource ID and save it to disk
```bash
> app-store-connect get-profile 5GJJFH4V5F --save  
Get Profile 5GJJFH4V5F
-- Profile --
Id: 5GJJFH4V5F
Type: profiles
Name: io codemagic capybara cbbdeb5a-a7bf-4ebc-921c-e1ae756b69c1 ios_app_development 1619508881
Platform: IOS
Uuid: 603669b0-1807-404f-9f04-7c7798b05274
Created date: 2021-04-27 07:34:41+00:00
State: ACTIVE
Type: IOS_APP_DEVELOPMENT
Expiration date: 2022-04-27 07:34:41+00:00
Content: "..."
Saved Profile IOS_APP_DEVELOPMENT profile 603669b0-1807-404f-9f04-7c7798b05274 to '/Users/priit/Library/MobileDevice/Provisioning …
```

Feature: add new action `app-store-connect get-profile`

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/signing_certificate.py

App Store Connect API responses that return [Certificate](https://developer.apple.com/documentation/appstoreconnectapi/certificate) resource are not including `passTypeId` relationship that we need to support.
```python
File "/usr/local/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 188, in invoke_cli
File "/usr/local/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 156, in _invoke_action
File "/usr/local/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 441, in wrapper
File "/usr/local/lib/python3.8/site-packages/codemagic/tools/app_store_connect.py", line 683, in fetch_signing_files
certificates = …
```

Bugfix: Allow passTypeId relationship for certificate resource

---

tests/models/junit/test_xml_generation.py

Unit test `test_xml_generation.test_xml` was unstable due to XML formatting where expected XML had attributes in one order, but the generated XML had the same attributes in different order.

CI: Unstable test due to XML formatting

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py

Actions `app-store-connect get-latest-app-store-build-number` and `app-store-connect get-latest-testflight-build-number` are unable to return the latest build number if some of the matched builds have non-integer version. For example latest TestFlight build number for given TestFlight submission is ought to be 10.7.4.1:
But
```shell
> app-store-connect get-latest-testflight-build-number 1531514033 --pre-release-version=2.0.1
Found 2 Builds matching specified filters: app=1531514033, version=2.0.1.
```
exists without returning/outputting any build numbers.

Bugfix: non-integer version codes in latest build numbers

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

To just validate and upload application package to App Store Connect we don't need App Store Connect API key in case Apple ID and password are provided for publishing. However, as it is currently implemented, as soon as binary upload is completed with `altool`, the tool tries to locate the build from App Store Connect, which was just created, but this will require interacting with App Store Connect API which is not possible using Apple ID and password. Make sure not to call App Store Connect API in case submitting to TestFlight with `--testflight` option is not specified.

Bugfix: App Store Connect publishing without API key

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py
tests/tools/app_store_connect/conftest.py
tests/tools/app_store_connect/test_from_cli_args.py
tests/tools/app_store_connect/test_get_latest_build_number.py
tests/tools/app_store_connect/test_publish_action.py

In case there are no builds maching the constraints given to actions `app-store-connect get-latest-app-store-build-number` and `app-store-connect get-latest-testflight-build-number` they fail with `ValueError`:
```python
[11:51:05 02-06-2021] ERROR cli_app.py:113 > Exception traceback:
File "/Users/priit/nevercode/cli-tools/src/codemagic/cli/cli_app.py", line 188, in invoke_cli
File "/Users/priit/nevercode/cli-tools/src/codemagic/cli/cli_app.py", line 156, in _invoke_action
File "/Users/priit/nevercode/cli-tools/src/codemagic/cli/cli_app.py", line 441, in wrapper
File "/Users/priit/nevercode/cli-tools/src/codemagic/tools/app_store_connect.py", line 275, …
```

Bugfix: ValueError on get latest build number in case of no builds

---

CHANGELOG.md
doc.py
docs/app-store-connect/publish.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py
tests/tools/app_store_connect/test_publish_action.py

In some rare cases validating application packages with `altool --validate-app` fails with ambiguous error messages, while the upload itself via `altool --upload-app` succeeds without any issues. To accomodate this usecase add an optional switch to `app-store-connect publish` action to omit the validation phase. It can be turned on either by passing `--skip-package-validation` flag to command invocation, or by setting `APP_STORE_CONNECT_SKIP_PACKAGE_VALIDATION` environment variable.
Example usages:
- By defining environment variable:
```shell
> APP_STORE_CONNECT_SKIP_PACKAGE_VALIDATION='true' app-store-connect publish
Searching for files matching /Users/priit/nevercode/cli-tools/src/**/*.ipa
Searching for files matching /Users/priit/nevercode/cli-tools/src/**/*.pkg
Publish …
```

Featue: Add option to skip binary validation for `app-store-connect publish` action

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/altool/altool.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

When we fail to parse the output of `altool` during `app-store-connect publish` call, then the full action can fail, which is not desirable:
```shell
> app-store-connect publish --path /Users/builder/clone/build/ios/ipa/banaan.ipa --key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER --issuer-id @env:APP_STORE_CONNECT_ISSUER_ID --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY
Publish "/Users/builder/clone/build/ios/ipa/banaan.ipa" to App Store Connect
App name: Banaan
Bundle identifier: io.codemagic.banaan
Certificate expires: 2022-05-14T14:35:20.000+0000
Distribution type: App Store
Min os version: 10.1
Provisioned devices: N/A
Provisions all devices: No
Supported platforms: iPhoneOS
Version code: 1.0.50
Version: 1.0
Validate "/Users/builder/clone/build/ios/ipa/banaan.ipa" for App Store Connect …
```

Bugfix: Make altool output parsing less strict

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

Once builds are uploaded to App Store Connect it can take quite a bit of time until they are properly processed for next steps
such as creating Beta App Review Submission. Add simple retrying logic to wait until builds are processed.
Example output from the updated action:
```shell
> app-store-connect publish --path ~/Downloads/banaan.ipa --testflight                                                                             1 ↵
Publish "/Users/priit/Downloads/banaan.ipa" to App Store Connect
App name: Banaan
Bundle identifier: io.codemagic.banaan
Certificate expires: 2022-05-14T04:35:20.000+0000
Distribution type: App Store
Min os version: 10.1
Provisioned devices: N/A
Provisions all devices: No
Supported platforms: iPhoneOS
Version code: 1.0.56
Version: 1.0
Validate …
```

Bugfix: Fix submitting builds to TestFlight

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

Since there is no TestFlight for macOS packages we should omit them from being submitted to TestFlight.

Bugfix: Do not submit macOS packages to TestFlight

---

CHANGELOG.md
README.md
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py

These error messages are returned when `--certificate-key` is not provided. This is really easy to confuse with App Store Connect `--private-key`, which can mislead users.
I've also updated the README to make it clear these tools are useful outside of codemagic.io.

Update error messages

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/argument/typed_cli_argument.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py

After uploading binaries to App Store Connect it can take a while before builds are completely processed and can be submitted to external testing in TestFlight. There used to be a fixed 10 minute timeout for waiting until the build processing completes by Apple, but in practise ofterntimes it is not enough. This pull request bumps the default timeout to 20 minutes and adds configuration option to either decrease or increase this value by either using
- command line option `--max-build-processing-wait <minutes>`,
- or specifying environment variable `APP_STORE_CONNECT_MAX_BUILD_PROCESSING_WAIT=<minutes>`.
Example build in [Codemagic](https://codemagic.io) using [this](https://github.com/priitlatt/banaan-ios/blob/f5ea5bc26554c53b10722c10bf0a310918132703/codemagic.yaml) configuration:

Feature: Add option to configure max allowed duration for build processing by Apple for TestFlight submit

---

CHANGELOG.md
docs/app-store-connect/beta-build-localizations/create.md
docs/app-store-connect/beta-build-localizations/list.md
docs/app-store-connect/beta-build-localizations/modify.md
docs/app-store-connect/publish.md
src/codemagic/tools/_app_store_connect/arguments.py
tests/tools/app_store_connect/test_publish_action.py

Currently help messages often use the shorthand flags for examples, but they are not always self-explanatory and can cause confusion. With the changes introduced in this pull request we now show the long version of CLI flag first in help messages and online documentation to reduce ambiguity. For example use `--testflight` instead of `-t` in help messages.

Improve help messages and online documentation

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
src/codemagic/cli/cli_app.py
src/codemagic/google_play/resources/enums.py
tests/apple/resources/enums/test_resource_enum.py

Due to changes introduced in PR #100 all enumeratations defined in `codemagic.apple.resources` are _loosely_ defined and all values are accepted as valid inputs. This causes CLI options with enum values to fall apart in case invalid enumeration is entered. For example:
```bash
$ app-store-connect publish --locale invalid-locale
usage: app-store-connect publish [-h] [--log-stream {stderr,stdout}] [--no-color] [--version] [-s] [-v] [--path artifact-path [artifact-path ...]] [-u APPLE_ID]
[-p APP_SPECIFIC_PASSWORD] [-t]
[-l {da,de-DE,el,en-AU,en-CA,en-GB,en-US,es-ES,es-MX,fi,fr-CA,fr-FR,id,it,ja,ko,ms,nl-NL,no,pt-BR,pt-PT,ru,sv,th,tr,vi,zh-Hans,zh-Hant}] [-n WHATS_NEW]
[--skip-package-validation] [--max-build-processing-wait MAX_BUILD_PROCESSING_WAIT] [--log-api-calls] [--json] [--issuer-id …
```

Bugfix: CLI argument error messages on invalid enum inputs 

---

CHANGELOG.md
docs/app-store-connect/beta-build-localizations/create.md
docs/app-store-connect/publish.md
src/codemagic/__version__.py
src/codemagic/apple/resources/beta_app_localization.py
src/codemagic/apple/resources/beta_app_review_submission.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/action_groups/beta_build_localizations_action_group.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py

Actions `app-store-connect publish` and `app-store-connect beta-build-localizations create` defined a hardcoded default value `en-US` for `--locale` option. However, not all application entries in App Store Connect have `en-US` as the primary localization, which makes this decision kind or arbitrary. In order to better suit actual user needs and make the tool more user-friendly, omit default value entirely and when adding testing/what's new notes to build, find out what the application's primary test information locale is, and reuse that value.
Additionally, beta build localization resource is automatically created for default locale soon after the build itself is submitted to App Store Connect. In that case we just need to modify the resource. To better accomodate such case, make …

Resolve default locale from applicaiton test information

---

CHANGELOG.md
Pipfile
Pipfile.lock
setup.py
src/codemagic/__version__.py

Module `urllib3` had a security issue [CVE-2021-33503](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503) that was fixed in [version 1.26.5](https://github.com/urllib3/urllib3/releases/tag/1.26.5). Update `requests` dependency in order to trigger `urllib3` update.

Dependencies: requests and urllib3 versions

---

CHANGELOG.md
doc.py
docs/app-store-connect/publish.md
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
src/codemagic/cli/argument/typed_cli_argument.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/action_groups/beta_build_localizations_action_group.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/_app_store_connect/resource_printer.py
src/codemagic/tools/app_store_connect.py
tests/apple/resources/enums/test_resource_enum.py
tests/tools/app_store_connect/arguments/test_beta_build_localizations.py
tests/tools/app_store_connect/test_from_cli_args.py
tests/tools/app_store_connect/test_publish_action.py
tests/tools/test_google_play.py

**Summary of the changes:**
The action `app-store-connect publish` already allowed submitting release notes, or _what's new_ notes in App Store Connect UI terms, to uploaded builds. But there was a limitation that you could only specify the notes for a single language using `--whats-new` flag. Often times this is not enough and you'd want to automate the full process of beta release cycle for whatever languages/locales you have. With the changes introduced in this pull request `app-store-connect publish` gets a new option `--beta-build-localizations` that takes JSON encoded list of locales and notes (as seen below in the example) and automates release notes creation for all given languages.
**Related changes:**
- Make `--whats-new` option independent from `--testflight` for …

Feature: Support multiple beta build localizations for TestFlight publishing

---

CHANGELOG.md
docs/keychain/README.md
docs/keychain/initialize.md
docs/keychain/use-login.md
src/codemagic/__version__.py
src/codemagic/tools/keychain.py

Fixes #126.
Avoid creating temporary keychains in `$TMPDIR` that get deleted with system reboots, which in turn messes up default keychain settings by prompting errors like
> Keychain "<keychain_name>" cannot be found to store "<secret_name">.
Your keychain may have been renamed, deleted, or it's on a unmounted volume.
Instead store the keychains generated by `keychain initialize` in `~/Library/Keychains/codemagic-cli-tools/*.keychain-db` by default.
Also add a new action `keychain use-login` to easily make the default login keychain from `~/Library/Keychains` system default keychain again.
**New actions:**
- `keychain use-login`
**Example usage of new action:**
```shell
> keychain use-login  
Use login keychain /Users/priit/Library/Keychains/login.keychain-db as system default keychain …
```

Do not create keychains to temporary directory by default

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

Multiple users reported frequent timeouts when attempting to submit release notes and submitting build to TestFlight. In this PR, I double the number of attempts to find an uploaded build on App Store Connect side.

Improvement: Finding build timeout

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/api_client.py
src/codemagic/apple/app_store_connect/apps/apps.py
src/codemagic/apple/app_store_connect/builds/builds.py
src/codemagic/apple/resources/app.py
src/codemagic/tools/_app_store_connect/action_groups/apps_action_group.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

Pagination of App Store Connect API endpoint [List All Builds of an App
](https://developer.apple.com/documentation/appstoreconnectapi/list_all_builds_of_an_app) does not work and instead or returning all unique builds across all pages, there are duplicates in pages and not all builds are returned.
Result with current implementation using list app builds:
```bash
$ app-store-connect apps builds 1496105355 | grep Id | sort | uniq -c | sort -n | tail -3
Get Builds for App 1496105355
Found 150 Builds for App
3 Id: d0a20499-3234-459b-9d76-387054f5f85c
3 Id: ee655964-6174-4cf2-9c0f-895fde55a797
3 Id: f7f67034-3585-483b-b591-17409e3b40b1
```
With the fix:
```shell
$ app-store-connect apps builds 1496105355 | grep Id | sort | uniq -c | sort -n | tail -3
Found 105 Builds matching specified …
```

Bugfix: Fix listing all builds for an app

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/resource.py
tests/apple/resources/conftest.py
tests/apple/resources/mocks/mock_resource.json
tests/apple/resources/test_undefined_resource_fields.py

Yet again App Store Connect API has changed without any documentation about it. This time [`BetaAppReviewSubmission.Attributes`](https://developer.apple.com/documentation/appstoreconnectapi/betaappreviewsubmission/attributes) comes with `submittedDate` in the response body, which as of 12.08.21, is not reflected by Apple's API docs.
Changes such as these break our strict mapping of API responses to Python objects and as a result full command invokation can fail unexpectedly. To be more flexible about such changes in API responses we now dynamically initialize only known model attributes and log the presence of unknown fields to a file.
The changes introduced here are are extension to what was already implemented in PR #100 for model relationships.
Example log entries from the test runs: …

Improvement: Add graceful handling for undefined App Store Connect model attributes

---

CHANGELOG.md
docs/app-store-connect/apps/list.md
docs/app-store-connect/builds/add-beta-test-info.md
docs/app-store-connect/builds/submit-to-testflight.md
docs/app-store-connect/publish.md
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/builds/builds.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/action_groups/apps_action_group.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py
tests/tools/app_store_connect/test_publish_action.py

Create new actions based on two steps from `publish` action:
* `app-store-connect builds add-beta-test-info` -- submission of localized What's new notes
* `app-store-connect builds submit-to-testflight` -- build submission to TestFlight
Both actions may now be used independently
✅ `add-beta-test-info`
```
Successfully modified Beta Build Localization 9f74c7d7-006d-4f5b-b8e6-866a0645cf4f
-- Beta Build Localization --
Id: 9f74c7d7-006d-4f5b-b8e6-866a0645cf4f
Type: betaBuildLocalizations
Locale: en-US
Whats new: What is new in English
```
✅ `submit-to-testflight`
```
Processing of builds by Apple can take a while, the timeout for waiting the processing to finish for build d5ea4bb8-9a4f-4d48-8fb3-4ee0db18a5c1 is set to 20 minutes.
Processing build d5ea4bb8-9a4f-4d48-8fb3-4ee0db18a5c1 is …
```

Improvement: add auxiliary submission actions

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py

With previous implementation it was rather cumbersome to use `AppStoreConnect.beta_build_localizations` directly from Python since `beta_build_localizations` argument accepted only `Types.BetaBuildLocalizations` objects as values. To overcome this limitation also add possibility to directly pass `List[BetaBuildInfo]` as beta_build_localizations:
```python
from codemagic.tools import AppStoreConnect
from codemagic.tools.app_store_connect import BetaBuildInfo
from codemagic.apple.resources import Locale
AppStoreConnect(...).add_beta_test_info(
build_id=...,
beta_build_localizations=[BetaBuildInfo(whats_new='What is new ...', locale=Locale.EN_US)]
)
```

Improve `AppStoreConnect.add_beta_test_info` Python API

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/error_response.py
tests/apple/resources/conftest.py
tests/apple/resources/mocks/error_response_with_links.json
tests/apple/resources/test_error_response.py

App Store Connect API errors now can contain an [undocumented](https://developer.apple.com/documentation/appstoreconnectapi/errorresponse/errors) `links` field in `ErrorResponse.Error` object, which caused exception on error handling:
```python
[2021-08-18 22:01:57,599: INFO/ForkPoolWorker-2] >>> GET https://api.appstoreconnect.apple.com/v1/bundleIds {'limit': 100, 'sort': 'name'}
[2021-08-18 22:01:57,938: INFO/ForkPoolWorker-2] <<< 403 {'errors': [{'id': 'XHI3JTPAXPXMTCWTY6RJMMMZUI', 'status': '403', 'code': 'FORBIDDEN.REQUIRED_AGREEMENTS_MISSING_OR_EXPIRED', 'title': 'A required agreement is missing or has expired.', 'detail': 'This request requires an in-effect agreement that has not been signed or has expired.', 'links': {'see': '/agreements'}}]}
[2021-08-18 22:01:57,965: …
```

Bugfix: App Store Connect API error responses with links

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

Action `app-store-connect build submit-to-testflight` fails with unexpected `ValueError` in case the application for which build is being submitted to testflight does not have all required test information filled in. Handle the thrown `ValueError` and raise `AppStoreConnectError` in place of it so that the process is terminated properly.

Bugfix: App Store Connect test info validation

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/application_package/ipa.py

Initializing `Ipa` models from packages that are compressed using `LZFSE` algoritm results in the following error:
```python
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.9.1-py3.7.egg/codemagic/models/application_package/ipa.py", line 23, in _validate_package
return bool(self.info_plist)
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.9.1-py3.7.egg/codemagic/models/application_package/ipa.py", line 71, in info_plist
return self._get_info_plist()
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.9.1-py3.7.egg/codemagic/models/application_package/ipa.py", line 65, in _get_info_plist …
```

Bugfix: Ipas compressed with LZFSE algorithm

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/resources/app.py

`ciProduct` relationship on `App` model is not quaranteed to be present:
```python
Task raised unexpected: TypeError("__init__() missing 1 required positional argument: 'ciProduct'")
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/usr/src/app/tasks/distribution.py", line 101, in process_distribution_task
new_status = TaskProcessor(db, raw_task).process()
File "/usr/src/app/distribution/task_processor.py", line 110, in process
return self.process()
File "/usr/src/app/distribution/task_processor.py", line 97, in process …
```

Bugfix: Make `ciProduct` relationship on `App` model optional

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/certificate.py
tests/models/test_certificate.py

Add `get_fingerprint` method to `codemagic.models.Certificate` class which returns certificate's hexadecimal fingerprint for requested hashing algorithm.
For example:
```python
>>> certificate_path = ...
>>> certificate = Certificate.from_p12(open(certificate_path, 'rb').read())
>>> certificate.get_fingerprint(hashes.SHA1())
'A402B132CDF1F7A040E71DB870EA39AA952F3852'
>>> certificate.get_fingerprint(hashes.SHA256())
'7D4B15F11DC4077CDF0E7DE05574FC3FC8F53E06321C10FFDF75ED370862D0BF'
```

Feature: Add method to obtain certificate fingerprint

---

CHANGELOG.md
docs/app-store-connect/README.md
docs/app-store-connect/beta-groups/add-build.md
docs/app-store-connect/list-devices.md
docs/app-store-connect/register-device.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/app_store_connect.py

There already was client method available for registering iOS and macOS devices to Apple Development team using [Register a New Device](https://developer.apple.com/documentation/appstoreconnectapi/register_a_new_device) API, but there was no CLI access to it. This PR addes capabilities to register new devices using CLI:
```shell
$ app-store-connect register-device \
--udid 00008101-000960143488001E \
--name "White iPhone 12 mini"
Creating new Device: udid: 00008101-000960143488001E, name: 'White iPhone 12 mini', platform: IOS
-- Device (Created) --
Id: P2U5FJ7DX4
Type: devices
Class: IPHONE
Model: iPhone 12 mini
Name: White iPhone 12 mini
Platform: IOS
Status: ENABLED
Udid: 00008101-000960143488001E
Created Device P2U5FJ7DX4
```

Feature: Add new action `app-store-connect register-device`

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/cli_process.py
src/codemagic/cli/cli_process_stream.py
tests/cli/test_cli_process.py

In most cases the tools provided by this module are actually just more user-friendy wrappers for some other executables in the system. As such, much of the heavylifting is done by the [`CliProcess`](https://github.com/codemagic-ci-cd/cli-tools/blob/326787ce788282ad88a0aa62d0ca4a6c98e98c2f/src/codemagic/cli/cli_process.py) class, which unfortunately currently does not work on Windows: 
```python
In [1]: from codemagic.cli import CliProcess
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-dbc669446119> in <module>
----> 1 from codemagic.cli import CliProcess
c:\users\administrator\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\codemagic\cli\__init__.py in <module>
6 …
```

Support command execution on Windows

---

Pipfile.lock

Mozilla Bleach version became outdated and started failing CI jobs. See an example [action run](https://github.com/codemagic-ci-cd/cli-tools/actions/runs/1407196347).

Dependencies: Update outdated development packages

---

CHANGELOG.md
docs/app-store-connect/publish.md
src/codemagic/__version__.py
src/codemagic/cli/cli_app.py
src/codemagic/models/altool/altool.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py

In order to get better insight about the update or validation failures during `app-store-connect publish`, add an option to launch `altool` invocation with `--verbose` flag.
Example usage:
```shell
$ app-store-connect publish \
--path app.ipa \
--key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER \
--issuer-id @env:APP_STORE_CONNECT_ISSUER_ID \
--private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
--verbose-altool-logging
```
Or using an environment variable to configure this option
```shell
$ export APP_STORE_CONNECT_VERBOSE_ALTOOL_LOGGING=true
$ app-store-connect publish \
--path app.ipa \
--key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER \
--issuer-id @env:APP_STORE_CONNECT_ISSUER_ID \
--private-key @env:APP_STORE_CONNECT_PRIVATE_KEY
```

Feature: altool verbose logs

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/cli_process_stream.py

In case there are byte sequences in the invoked subprocess output that do not have unicode representation, then unexpected `UnicodeDecodeErrors` might occur while decoding those byte chunks. An example stacktrace is as follows:
```python
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.9.1-py3.7.egg/codemagic/tools/_app_store_connect/actions/publish_action.py", line 88, in publish
self._publish_application_package(altool, application_package, validate_package)
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.9.1-py3.7.egg/codemagic/tools/_app_store_connect/actions/publish_action.py", line 116, in _publish_application_package …
```

Bugfix: decoding undefined byte sequences in process streams

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/argument/typed_cli_argument.py
tests/tools/app_store_connect/test_from_cli_args.py
tests/tools/app_store_connect/test_publish_action.py
tests/tools/test_google_play.py

In case invalid argument value (either by validation standards or type mismatch) is provided for CLI action via environment variables, then the invoked action fails unexpectedly with status code 9 and no appopriate error message.
For example if App Store Connect API key is defined via environment variables, then `app-store-connect` commands fail unexpectedly like
```shell
$ APP_STORE_CONNECT_PRIVATE_KEY="invalid private key" app-store-connect apps list
Executing AppStoreConnect action apps failed unexpectedly. Detailed logs are available at "/var/folders/vs/tcrc5cns67zgynxt6fssjdg80000gn/T/codemagic-24-11-21.log". To see more details about the error, add `--verbose` command line option.
```
From the logs we can see that handling invalid argument failed:
```log
[12:40:16 24-11-2021] DEBUG …
```

Bugfix: Gracefully handle invalid arguments from environment variables

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/altool/enums.py
src/codemagic/models/application_package/ipa.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
tests/models/altool/test_altool_retrying.py
tests/tools/app_store_connect/test_publish_action.py

When uploading ipas built for tvOS with `app-store-connect publish` then the `altool` validation and upload commands are incorrectly using `ios` for `--type` flag:
```shell
xcrun altool --upload-app \
--file /path/to/tvOS.ipa \
--type ios \
--apiKey "${API_KEY_IDENTIFIER}" \
--apiIssuer "${API_KEY_ISSUER}" \
--output-format json
```
This is due to very superficial logic that only takes file extension into account when package type is inferred. To fix type detection for ipas, check its the supported platforms.

Bugfix: tvOS ipas are validated and uploaded as iOS apps with `altool`

---

CHANGELOG.md
docs/app-store-connect/publish.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py
tests/tools/app_store_connect/test_publish_action.py

Oftentimes, when submitting application package to App Store Connect via `app-store-connect publish`, the package validation command, which is invoked by running
```
xcrun altool --validate-app --file /path/to/app.ipa ...
```
fails due to
- Apple services being unavailable,
- Apple is not capable of validating the package because of `"Unable to process app at this time due to a general error"`,
- vague authentication failure.
And all this happens despite the fact that actually the very same binary can be uploaded just fine in case validation is disabled.
In order to avoid such false alarms about validation failures, **disable package validation by default** (previously it was enabled by default), and leave option to turn in on by using a CLI option `--enable-package-validation`.
**Updated …

Deprecation: Ignore --skip-package-validation option for `app-store-connect publish`

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py

In case localized App Store version information cannot be created or updated for some langugae as part of `app-store-connect builds submit-to-app-store`, then do not fail the whole action. Instead process the error and log it as an acknowledgement. 
**Affected actions:**
- `app-store-connect publish` (in case App Store review submission is enabled),
- `app-store-connect builds submit-to-app-store`.

Bugfix: Action `submit-to-app-store` crashes if updating/creating meta for locale fails

---

.github/workflows/run-checks.yml
CHANGELOG.md
Pipfile
Pipfile.lock
setup.py

With [PyJWT](https://pyjwt.readthedocs.io/en/stable/index.html) version 2.0.1 `app-store-connect` commands can fail unexpectedly due to
```python
File "/Users/priit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 200, in invoke_cli
File "/Users/priit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 156, in _invoke_action
File "/Users/priit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 412, in wrapper
File "/Users/priit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/codemagic/tools/app_store_connect.py", line 689, in fetch_signing_files …
```

Dependencies: Update minimal PyJWT dependency to 2.3.0

---

CHANGELOG.md
src/codemagic/apple/app_store_connect/api_client.py
src/codemagic/apple/app_store_connect/api_session.py
src/codemagic/apple/app_store_connect/json_web_token_manager.py
tests/apple/app_store_connect/test_api_session.py

Improvements to App Store Connect JSON web token management.
- Include App Store Connect API key identifier in verbose log to indicate for which keys JSON web token is either generated or loaded from cache.
- Revoke invalid JSON web token when unauthorized request retries are exhausted so that the same token will not be used for subsequent command invocations from disk cache.

Improvement: App Store Connect JWT cache logging and lifecycle

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/arguments.py

Due to changes in [PR #196](https://github.com/codemagic-ci-cd/cli-tools/pull/196) only PEM encoded keys were accepted as certificate keys, but OpenSSH keys are not fully compatible with the PEM standard, and should be allowed too.
Consider OpenSSH private keys for `app-store-connect` argument `--certificate-key` valid again.

Bugfix: Allow OpenSSH keys for certificate private key

---

CHANGELOG.md
src/codemagic/apple/resources/enums.py
src/codemagic/tools/app_store_connect.py

There is a bug in `app-store-connect fetch-signing-files` action related to provisioning profile creation. When requested AdHoc or development provisioning profile, that is profiles that can contain allowed devices identifiers, does not exist then the tool automatically tries to include all eligible devices registered in Apple Developer Portal in the new profile during creation.
However, up until now Apple TV devices were also included when iOS provisioning profiles were created, which is not allowed, despite the fact that devices Apple TV devices share the same [platform attribute](https://developer.apple.com/documentation/appstoreconnectapi/device/attributes) with iPhones, iPads, iPods and Apple Watches.
This makes the [Create a …

Bugfix: Ignore uncompatible devices when creating provisioning profiles

---

CHANGELOG.md
src/codemagic/apple/resources/enums.py
src/codemagic/tools/app_store_connect.py

Continuation to the improvements first introduced in #185. There the default certificate type for iOS App distribution provisioning profiles was changed from iOS Distribution to Distribution so that single certificate could be used for provisioning profiles targeting different platforms.
Similar change can be also made for iOS App AdHoc profiles. Up until now iOS AdHoc profiles were mapped to iOS Distribution certificates, but those too can use the platform-independent Distribution certificates. So, with the changes here
provisioning profiles of type `IOS_APP_ADHOC` are assigned certificates with type `DISTRIBUTION` (as opposed to `IOS_DISTIBUTION` which was used before), when downloaded (or created) using action `app-store-connect fetch-signing-files`. This allows reusing one signing …

Feature: Use "Distribution" certificate for iOS App AdHoc profiles

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/export_options.py
tests/models/test_export_options.py

Starting from Xcode 13 export options support new key named `manageAppVersionAndBuildNumber`. Read more about it from this [Apple Developer Forum thread](https://developer.apple.com/forums/thread/690647).
This key is not supported by `ExportOptions` class and as such executing `xcode-project build-ipa` will fail in case provided export options property list contains said key `manageAppVersionAndBuildNumber`. Full stacktrace for the error is as follows:
```python
File "/Users/builder/.pyenv/versions/3.8.7/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 200, in invoke_cli
File "/Users/builder/.pyenv/versions/3.8.7/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 156, in _invoke_action
return …
```

Bugfix: Add manageAppVersionAndBuildNumber to export options

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/code_signing_settings_manager.py
src/codemagic/models/export_options.py

Export options propertly list generation was broken with the changes introduced in #203. Namely, the `provisioningProfiles` mapping in export options possibly contained wrong bundle identifiers as mapping keys in case wildcard provisioning profiles were used. The keys (or bundle identifiers) were directly taken from used provisioning profiles instead of using the actual bundle identifiers from the Xcode project targets to which the profiles were assigned to.
An example. When wildcard profile with identifier `*` was used for `xcode-project use-profile`, then the options for exporting the project were generated as
```
- Method: development
- Provisioning Profiles:
- *: XC Wildcard ios_app_development 1645605003
- Signing Certificate: iPhone Developer
- Signing Style: manual
- Team Id: …
```

Bugfix: Export options plist generation for wildcard profiles

---

CHANGELOG.md
docs/app-store-connect/create-certificate.md
docs/app-store-connect/get-certificate.md
src/codemagic/__version__.py
src/codemagic/cli/argument/common_argument_types.py
src/codemagic/models/certificate.py
src/codemagic/models/private_key.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/app_store_connect.py
tests/models/test_private_key.py

The aim of this pull request is to make the Python API more user friendly for private key and certificate management. Additionally make `AppStoreConnect` class methods that implement `app-store-connect` actions which manage certificate easier to use by allowing directly plugging in `PrivateKey` instances in stead of having to use `Types.CertificateKeyArgument` type wrapper.
**Notable changes:**
- Add new factory method for `PrivateKey` to load the key from PKCS#12 containers.
- Add option to specify save path for certificates downloaded using `app-store-connect` tool.
- Support `DSA` and elliptic curve private keys in addition to `RSA` keys for `PrivateKey`.
- `app-store-connect create-certificate`,
- `app-store-connect get-certificate`,
- `app-store-connect …

Make certificates and private keys handling more convenient 

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/py.typed

Include `py.typed` marker file to indicate that the package contains inlined type information. See more information from [PEP 561 -- Distributing and Packaging Type Information](https://www.python.org/dev/peps/pep-0561/).

Typing: Add `py.typed` marker file to indicate inline types

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/shell_tools/keytool.py
src/codemagic/tools/android_keystore/android_keystore.py
src/codemagic/tools/android_keystore/arguments.py

This is a bugfix PR to address issues that slipped through with `android-keystore` tool release.
The issues were:
- Action `android-keystore create-debug-keysotre` did not work since it called `create` method with invalid keyword argument.
- Argument `--keystore` was not required for actions `android-keystore create` and `android-keystore verify` which potentially caused unexpected failures when invoking those actions.
- When trying to verify non-keystore file as a keystore the shown error message contained Java classpaths and was misleading. The error is now more self-explanatory.  
**Affected actions:**
- `android-keystore create`,
- `android-keystore create-debug-keystore`,
- `android-keystore verify`.

Bugfix: Address issues in `android-keystore` tool

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/certificate.py
tests/models/test_certificate.py

This PR contains a small bugfix for `codemagic.models.Certificate` class.
Namely _Mac Development_ code signing certificates, which are used to code sign development versions of Mac apps were not detected as development certificates and the property `Certificate.is_development_certificate` returned `False` in case of such certificates.
This change does not affect any of the command line actions.

Bugfix: Mac Development certificates are not recognized as development certificates

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/google_play/resources/resource.py
src/codemagic/google_play/resources/track.py
tests/google_play/resources/test_resource_print.py

This fixes #208.
Action `google-play get-latest-build-number` uses Google Play Developer API method [`edits.tracks.get`](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/get) to obtain the latest build build number in certain release track.
While API documentation indicates that the response for [`Track`](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks) resource should contain a list of [`Release`](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#Release) objects that all have reference to [`CountryTargeting`](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks#CountryTargeting) which has a field called `includeRestOfWorld`, in reality the `includeRestOfWorld` field might not be …

Bugfix: `google-play get-latest-build-number` crashes on incomplete response

---

CHANGELOG.md
docs/xcode-project/use-profiles.md
src/codemagic/__version__.py
src/codemagic/models/export_options.py
src/codemagic/tools/_xcode_project/arguments.py

When building Xcode projects that use App Clips it is necessary to specify `distributionBundleIdentifier` in export options property list for exporting the `xcarchive`. Right now setting this export option results in the following error:
```python
[15:13:58 29-04-2022] ERROR cli_app.py:113 > Exception traceback:
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.24.1-py3.7.egg/codemagic/cli/cli_app.py", line 200, in invoke_cli
File "/Users/priit/.virtualenvs/cli-tools-shZ38mB-/lib/python3.7/site-packages/codemagic_cli_tools-0.24.1-py3.7.egg/codemagic/cli/cli_app.py", line 156, in _invoke_action
File …
```

Bugfix: Allow configuring `distributionBundleIdentifier` export option

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/cli_process.py
src/codemagic/models/xctests/xcresulttool.py

In case Xcode project has a lot of tests, then parsing test result information from generated `xcresult` bundle can become relatively slow. This is because underlying conversion command
```shell
xcrun xcresulttool get --format json --path '/path/to/TestSuite.xcresult' --id '...'
```
to transform binary test results included in the bundle to `JSON` format can generate a lot of output (30+ MB at 500K+ lines).
Evidently processing this kind of text output in Python via small (8KB) chunks is not the most efficient way to deal with it. As the output is only needed as a whole once the command is completed, then it makes sense to pipe it directly to a file, and finally read the generated JSON from this file once processing is completed.
- `xcode-project run-tests`
- …

Improvement: `xcresult` test result parsing speedup

---

Pipfile
Pipfile.lock
src/codemagic/tools/keychain.py

Bump `pyOpenSSL` package requirement from version `19.x.y` to `22.z.w` for development environment.

Dependencies: Update `pyOpenSSL` version requirement for development

---

.github/workflows/run-checks.yml
tests/apple/app_store_connect/apps/test_apps.py
tests/apple/app_store_connect/builds/test_builds.py
tests/conftest.py

Do not require actual App Store Connect authenticaiton information for running tests as it is not used anyway.

Tests: Add default values for App Store Connect client fixture

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/api_client.py
src/codemagic/apple/app_store_connect/versioning/__init__.py
src/codemagic/apple/app_store_connect/versioning/review_submission_items.py
src/codemagic/apple/app_store_connect/versioning/review_submissions.py
src/codemagic/apple/resources/__init__.py
src/codemagic/apple/resources/app_store_version.py
src/codemagic/apple/resources/enums.py
src/codemagic/apple/resources/review_submission.py
src/codemagic/apple/resources/review_submission_item.py
src/codemagic/tools/_app_store_connect/abstract_base_action.py
src/codemagic/tools/_app_store_connect/action_group.py
src/codemagic/tools/_app_store_connect/action_groups/__init__.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py
src/codemagic/tools/_app_store_connect/action_groups/review_submission_items_actions_group.py
src/codemagic/tools/_app_store_connect/action_groups/review_submissions_actions_group.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/_app_store_connect/resource_manager_mixin.py
src/codemagic/tools/app_store_connect.py
tests/apple/app_store_connect/versioning/test_review_submission_items.py
tests/apple/app_store_connect/versioning/test_review_submissions.py
tests/apple/resources/mocks/app_store_version.json

Apple has deprecated the [Create an App Store Version Submission](https://developer.apple.com/documentation/appstoreconnectapi/create_an_app_store_version_submission) and replaced it by [Review Submissions](https://developer.apple.com/documentation/appstoreconnectapi/review_submissions) API. Changes included in this PR update the logic driving App Store publishing as part of actions `app-store-connect publish` and `app-store-connect builds submit-to-app-store`.
**New actions**
- `app-store-connect review-submission-items create`
- `app-store-connect review-submissions cancel`
- `app-store-connect review-submissions confirm`
- `app-store-connect review-submissions create`
- `app-store-connect review-submissions get`
- `app-store-connect …

Bugfix: App Store review submission using `app-store-connect builds submit-to-app-store`

---

CHANGELOG.md
src/codemagic/tools/keychain.py
src/codemagic/tools/xcode_project.py

this makes the api behave more like the cli and makes it much easier to use.
currently in my code i have to do this, which isn't ideal and adds unnecessary bloat to my script:
```py
XcodeProject().use_profiles(
XcodeProjectArgument.XCODE_PROJECT_PATTERN.get_default(),
XcodeProjectArgument.PROFILE_PATHS.get_default(),
)
```

Development: Add default values to all  arguments in `add_certificates` and `use_profiles` declarations

---

CHANGELOG.md
bin/code_signing_manager.rb

Action `xcode-project use-profiles` is using Ruby script [`code_signing_manager.rb`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/bin/code_signing_manager.rb) under the hood to make changes to Xcode project files.
In there was bunch of custom made logic to retrieve bundle identifier value for Xcode project build configurations. This logic however fails to detect the bundle identifier in case build configuration inherits build settings from `xcconfig` configurations in some cases.
To make this component simpler and more robust, replace the custom code by [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) Ruby gem built-in method [`XCBuildConfiguration#resolve_build_setting method`](https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/XCBuildConfiguration#resolve_bui …

Bugfix: Update Xcode project bundle identifier resolving

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/cli/argument/argument.py
src/codemagic/cli/argument/argument_properties.py
src/codemagic/cli/argument/typed_cli_argument.py
tests/tools/app_store_connect/test_publish_action.py

Grouped CLI arguments that can be also defined via environment variables (not just CLI switches) can cause unexpected exceptions when invalid values are provided as environment variable value.
For example action `app-store-connect publish` has argument group "Apple's altool configuration options" that contains switch `--altool-retries`, which is supposed to be a positive integer. Its value can also be specified by environment variable `APP_STORE_CONNECT_ALTOOL_RETRIES`. It is expected that the same values either from CLI or from environment yield in exactly the same result, but it is not the case as of now. Invalid values from CLI args are handled properly
```shell
$ app-store-connect publish --path app.ipa --altool-retries -1
usage: app-store-connect publish [-h] [--log-stream …
```

Bugfix: Invalid values for grouped arguments via environment variables are not handled

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/altool/altool.py

Action `app-store-connect publish` uses `xcrun altool` to perform the package upload to App Store Connect. With some Xcode versions `altool` logs out all environment variables and their values as a Ruby hashmap in case of an error.
Usually this is not a desired behaviour, especially in a CI envioronment. This is because environment variables can contain various secrets such as private keys, passwords etc, and they would leak to build logs that way.
In order to tackle this, replace environment variable values in `altool` output with ellipsis. That is
```
ENV: {"VARIABLE_1" => "value", "KEY" => "other value"}
```
becomes
```
ENV: {"VARIABLE_1" => "...", "KEY" => "..."}
```
in the output.
Note that in the verbose logs full unmodified `altool` output is available for inspection.
**Updated …

Improvement: hide environment variables in `altool` output

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/models/junit/definitions.py
src/codemagic/tools/xcode_project.py

When running Xcode tests using action `xcode-project run-tests` by specifying `xcodebuild` flag `-retry-tests-on-failure`, then Xcode automatically retries failed tests. The testcases that initially failed, but succeded later during retry attempts are not considered as successful tests and contribute to overall test suite failure. This is not a desired outcome, and the action should take the retried attempts into account to resolve overall test execution status.
The changes in this PR will check if any of the failed or errored testcases had a successful retry attempt.
- `xcode-project run-tests`

Improvement: Check if failed tests were retried successfully

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/scripts/code_signing_manager.rb

Mechanism of how bundle identifiers are detected from Xcode projects for `xcode-project use-profiles` was changed in version [v0.27.0](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.27.0). Namely the script [`code_signing_manager.rb`](https://github.com/codemagic-ci-cd/cli-tools/pull/232/files#diff-d49c5b1f0a323fabce10f56a5b783485494ae12650faa1db910a8870bfdeeeb4) was edited and sadly those edits introduced some regressions.
In case bundle identifier is defined in information property list (Info.plist) file, then it will not be resolved from target's build configuration settings. As a result we don't know what bundle identifier corresponds to given build configuration, which in turn means that we cannot assign proper code signing settings to this configuration. Eventually …

Bugfix: Resolve bundle identifiers from Info.plist files for `xcode-project use-profiles`

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
src/codemagic/tools/app_store_connect.py

Currently, setting the parameter `--type` to `MAC_APP_DIRECT` when using `app-store-connect fetch-signing-files` results in the following error:
```python
File "/Users/builder/.pyenv/versions/3.8.7/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 202, in invoke_cli
File "/Users/builder/.pyenv/versions/3.8.7/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 158, in _invoke_action
File "/Users/builder/.pyenv/versions/3.8.7/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 417, in wrapper
File "/Users/builder/.pyenv/versions/3.8.7/lib/python3.8/site-packages/codemagic/tools/app_store_connect.py", line 756, in …
```

Bugfix: Match profile type and cert for MAC_APP_DIRECT

---

CHANGELOG.md
pyproject.toml

This PR adds the changelog URL to `pyproject.toml`, as per [poetry documentation](https://python-poetry.org/docs/pyproject/#urls).

Add Changelog URL to pyproject.toml

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/utilities/auditing/http_request_auditor.py

This PR is a follow up to PR #248 where structured failure information was introduced. 
Often times is also improtant to know when exactly which HTTP call failed, not only what the request and response were. Hence timestamps are included in the structured (failed) HTTP request logs.

Development: Save timestamp along with other failed App Store Connect HTTP request info

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/utilities/backwards_file_reader.py
tests/utilities/test_backwards_file_reader.py

In utilities package `codemagic.utilities.backwards_file_reader` there is a function `iter_backwards` that can be used to iterate over lines in file from bottom to top.
Currently it only works with files that are saved to disk and the function takes file path (as a string or `pathlib.Path` object) as an argument.
But in reality the files are not always saved to the disk, and can be stored in-memory. In such cases the path is not available and as a result `iter_backwards` function cannot be used.
Changes in this PR add support to iterate lines on file-like objects too.
**Examples of updated usage:**
- Iterate backwards over a file that is saved to disk</summary>
```python
import tempfile
from codemagic.utilities.backwards_file_reader import iter_backwards
with …
```

Development: Make `iter_backwards` work on file-like objects

---

CHANGELOG.md
pyproject.toml
src/codemagic/apple/app_store_connect/provisioning/profiles.py
src/codemagic/apple/resources/enums.py
src/codemagic/tools/app_store_connect.py
tests/apple/app_store_connect/provisioning/test_profiles.py
tests/apple/resources/enums/test_profile_type.py

When creating development and ad hoc provisioning profiles, Apple requires the existence of suitable test devices on the Apple Developer Portal.
Previous implementations did not check whether appropriate devices were included in the API call.
This lead to `409` responses from [App Store Connect API Create Profile](https://developer.apple.com/documentation/appstoreconnectapi/create_a_profile) endpoint. For example a `POST` request to the `https://api.appstoreconnect.apple.com/v1/profiles` endpoint with the following content:
```json
{
"data":{
"type":"profiles",
"attributes":{
"name":"profile name",
"profileType":"IOS_APP_DEVELOPMENT"
},
"relationships":{
"certificates":{
"data":[
{
"id":"13CO2HS7YE",
"type":"certificates"
}
]
},
"devices":{},
"bundleId":{
"data":{
"type":"bundleIds", …
```

Improvement: Show error message if devices are not provided on development or ad-hoc profile creation

---

CHANGELOG.md
pyproject.toml
src/codemagic/apple/app_store_connect/provisioning/profiles.py

The current code contains some dead links to Apple API documentation, which are being replaced in this pull request by docstrings to the resources under observation.
Docstrings are updated for the following definitions:
`Profiles.list_device_ids`
`Profiles.list_certificate_ids`
`Profiles.get_bundle_id_resource_id`
Closes [issue #237](https://github.com/codemagic-ci-cd/cli-tools/issues/237).

Docs: Replace docstrings for App Store Connect profiles provisioning

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/scripts/code_signing_manager.rb

When building iOS project for testing with `xcodebuild build-for-testing` while targeting real hardware it is required that UI testing targets are code signed. Otherwise the tests cannot be propery executed.
Without the changes in this PR `xcode-project use-profiles` did not configure code signing for Xcode build targets with product type `com.apple.product-type.bundle.ui-testing`. The modifications introduced here make sure that those targets are also assigned matching signing configuration, provided that suitable provisioning profiles exist.
- `xcode-project use-profiles`

Bugfix: Configure code signing for iOS UI testing targets

---

codemagic.yaml

Use Mac minis with M1 chip for Codemagic CI workflows to speed up the builds.

CI: Use M1 Mac minis for CI

---

CHANGELOG.md
docs/xcode-project/README.md
docs/xcode-project/build-ipa.md
docs/xcode-project/show-build-settings.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/xcodebuild.py
src/codemagic/tools/_xcode_project/arguments.py
src/codemagic/tools/xcode_project.py

Run `xcodebuild -showBuildSettings` as part of `xcode-project build-ipa`. This will print out all relevant information about the project that is being built.
By default, the output is available in file CLI tools logs.
To show build settings in terminal window (or in Codemagic), use `xcode-project build-ipa` with `--verbose` flag.
*Motivation: help with debugging iOS build failures*

Feature: log project build settings

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/codemagic/__version__.py
src/codemagic/cli/argument/typed_cli_argument.py
src/codemagic/tools/_app_store_connect/arguments.py

If `cryptography >= 38.0.0` is used, then all actions fail with the following stacktrace:
```python
File "/home/builder/.local/bin/codemagic-cli-tools", line 5, in <module>
from codemagic.tools import CodemagicCliTools
File "/home/builder/.local/lib/python3.8/site-packages/codemagic/tools/__init__.py", line 1, in <module>
from .android_app_bundle import AndroidAppBundle
File "/home/builder/.local/lib/python3.8/site-packages/codemagic/tools/android_app_bundle.py", line 12, in <module>
from codemagic.models import AndroidSigningInfo
File "/home/builder/.local/lib/python3.8/site-packages/codemagic/models/__init__.py", line 1, in <module>
from .altool import Altool
File "/home/builder/.local/lib/python3.8/site-packages/codemagic/models/altool/__init__.py", …
```

Dependencies: Set upper bound `<38.0.0` for `cyrptography` dependency

---

CHANGELOG.md
docs/xcode-project/use-profiles.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/_xcode_project/arguments.py

This is a follow up to PR #271 that fills in blanks that are required to prepare a release.
- update changelog,
- bump version number,
- regenerate markdown documentation.

Release info: Action `xcode-project use-profiles` action docs changes

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/certificate.py

PKCS#12 containers can be valid even if they do not contain any certificate entries in them. Furthermore, `cryptography`'s built-in `pkcs12.load_key_and_certificates`, which is used by `Certificate.from_p12`, has a return type `Optional[x509.Certificate]` for the returned certificate.
The factory method however expected that the given PKCS#12 container always contains the certificate, which is a false assumption, and did a mere `assert x509_certificate is not None`. This can lead to unexpected results:
- in production mode assertions are ignored altogether and a snowball effect could arise with issues deeper down the line,
- unexpected `AssertionError` is thrown in case assertions are enabled.
To overcome this, check that the certificate acquired from the container is usable, and raise a …

Bugfix: Remove `assert` from `Certificate.from_p12`

---

.github/workflows/run-checks.yml
CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/cli/action_group.py
src/codemagic/models/keystore.py

Fixes #282.
Python 3.11 introduced a more strict check for default values of `dataclass` fields: https://docs.python.org/3/whatsnew/3.11.html#dataclasses
Since `codemagic.models.Keystore` defined field `certificate_attributes` as
```python
@dataclass
class Keystore:
...
certificate_attributes: CertificateAttributes = CertificateAttributes()
```
where `CertificateAttributes` is dataclass on its own, this caused a `ValueError`.
<details>
<summary>Stacktrace</summary>
<pre>
>>> from codemagic.models import Keystore
File "<stdin>", line 1, in <module>
File "/Users/priit/.pyenv/versions/3.11.0/lib/python3.11/site-packages/codemagic/models/__init__.py", line 12, in <module>
from .keystore import Keystore
File …

Bugfix: Remove mutable default usage from Keystore model declaration

---

CHANGELOG.md
pyproject.toml

Closes https://github.com/codemagic-ci-cd/cli-tools/issues/286.
The current version of [`bundletool`](https://github.com/google/bundletool) is outdated and might cause issues for users with new projects.
In this PR, the `bundletool` version is pumped from [`0.15.0`](https://github.com/google/bundletool/releases/tag/0.15.0) to [`1.13.1`](https://github.com/google/bundletool/releases/tag/1.13.1)
**QA:**
- no breaking changes observed in `bundletool` release history 
- successful builds for a basic React Native and Flutter application using a [`codemagic`](https://codemagic.io/) pipeline with an upgraded version of `cli-tools` via PyPi test environment (version update and apk extraction from bundle) were run
The following `android-app-bundle` actions work as expected in a local environment …

Update bundletool version to 1.13.1

---

CHANGELOG.md
codemagic.yaml
pyproject.toml
src/codemagic/__version__.py

While GitHub provides static links to assets on latest releases, it would be difficult to use them for this repo since Python wheels as they include version in the filename by default.
To overcome that limitation upload a copy of the wheel with fixed name too.

CI: Update release jobs and artifact storage

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/cli/argument/argument.py
src/codemagic/cli/argument/argument_properties.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/android_app_bundle.py
src/codemagic/tools/android_keystore/arguments.py

Fixes #293.
The way how Python treats `NamedTuple`s in version 3.11.1 is slightly different to how it used to be before (including in 3.11.0).
Consider this snippet for example:
```python
import enum
import typing
class NT(typing.NamedTuple):
s: str
i: int
class E(NT, enum.Enum):
A = NT(s='a', i=1)
B = NT(s='b', i=A.i)
if __name__ == '__main__':
assert type(E.A.value) == NT
```
In Python versions <= 3.11.0 one could access the fields of already defined enumerations. In the example above `B` is essentially defined as `NT(s='b', i=1)`, but the value for `i` is taken from `A.i`, which is defined right above. However in Python 3.11.1 the type of `A` at that point is not `NT` as it used to be, but is plain `tuple` now. 
Consequently the snippet above runs fine with Python <= 3.11.0, but fail …

Bugfix: Python 3.11.1 compatibility

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py
tests/tools/app_store_connect/test_get_latest_build_number.py

Changes in this pull request fix the actions that detect the latest build number from App Store Connect for App Store or Pre Release (TestFlight) versions:
- `app-store-connect get-latest-testflight-build-number`,
- `app-store-connect get-latest-app-store-build-number` and 
- `app-store-connect get-latest-build-number`.
In previous versions if `--pre-release-version` or `--app-store-version` argument was omitted, then the global latest version for an app was detected only based on build versions, which can lead to wrong results. For example consider the case where we have
- TestFlight version `1.0.1` with builds `1`, `2`,`3` and 
- TestFlight version `1.0.0` with builds `1`, `2`, ..., `5`, `6`.
- TestFlight version `0.0.1` with builds ..., `5`, `999`.
In this case the expected latest …

Bugfix: App Store and Testflight latest build numbers

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/action_groups/builds_action_group.py

This PR fixes a bug introduced in #306.
In the scenario where the cancelling of previous submissions is delayed on Apple's side, the creation of new submissions will still fail as previously, even though the previous submission is cancelled.
The flag `--cancel-previous-submissions` for the `app-store-connect builds submit-to-app-store` action was updated to take this into account and wait for the response from Apple.
**QA:**
- submission with `--cancel-previous-submissions` flag waits for Apple's response and submission is successful ✅ 
- behaviour without specifying the flag is not changed and submission fails as usual ✅

Bugfix: wait for submissions to exit canceling state before creating a new submission

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/code_signing_settings_manager.py

Two invocations of `xcode-project use-profiles` can lead to different modifications to Xcode project files even though the very same set of provisioning profiles are discovered. This can happen because the script [`code_signing_manager.rb`](https://github.com/codemagic-ci-cd/cli-tools/blob/v0.38.1/src/codemagic/scripts/code_signing_manager.rb), which is used internally for updating `*.xcodeproj` files, depends on the order of provisioning profiles that are passed to it.
In order to avoid such inconsistencies, make sure that profiles are sorted in a stable manner before serializing them for `code_signing_manager.rb`. The changes in this PR ensure that profiles are ordered so that
- Non-wildcard/strict matching provisioning profiles have higher priority than wildcard profiles.
- The more …

Bugfix: Do not rely on provisioning profile ordering on disk for `xcode-project use-profiles`

---

CHANGELOG.md
docs/app-store-connect/README.md
docs/app-store-connect/get-latest-app-store-build-number.md
docs/app-store-connect/get-latest-build-number.md
docs/app-store-connect/get-latest-testflight-build-number.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py

Update documentation for actions
- `app-store-connect get-latest-build-number`,
- `app-store-connect get-latest-app-store-build-number`,
- `app-store-connect get-latest-testflight-build-number`.

Highest build  number of highest version uploaded

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/codemagic/__version__.py

Back when `codemagic-cli-tools` still had a direct dependency on both [`cryptography`](https://cryptography.io/en/latest/) and [`pyOpenSSL`](https://www.pyopenssl.org/en/latest/) libraries, then using `cryptography` version  `>= 38.0.0` caused 
```python
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```
arising from `OpenSSL.crypto` module.
Due to this an upper limit with constraint `<38.0.0` was enforced on `cryptography` in #268.
While direct dependency on `pyOpenSSL` was removed in #269 the constraint on `cryptography` version was never lifted.
Change in this PR removes upper bound from allowed `cryptography` versions making `codemagic-cli-tools` compatible with contemporary up-to-date releases of `cryptography`.

Dependencies: Remove upper bound from `cryptography` dependency

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/certificate.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/utilities/auditing/exception_auditor.py
src/codemagic/utilities/auditing/http_request_auditor.py

As per Python `datetime` [documentation](https://docs.python.org/3/library/datetime.html), due to the fact that naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing the current time in UTC is by calling `datetime.now(timezone.utc)`.

Use timezone aware datetimes

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/keychain.py

As `Keychain` methods except password argument to be passed as `Password` instance, it makes the Python API of `Keychain` really cumbersome to use. To make it more user friendly, also accept plain `str` values wherever `Password` is currently used.

Feature: Improve Python API for `Keychain` 

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google/google_client.py

In #317 a new tool called `firebase-app-distribution` was added.
Using the [Firebase App Distribution releases APIs](https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.apps.releases) requires `google-api-python-client >= 2.84.0`, but up until this PR Codemagic CLI tools onlyonly required version `1.7.12` of `google-api-python-client`, which is incompatible with recent Google APIs.
Too old `google-api-python-client` version caused the invocations of `firebase-app-distribution` commands to fail with error
```
Client error. name: firebaseappdistribution  version: v1
```

Dependencies: Update minumum `google-api-python-client` version

---

CHANGELOG.md
src/codemagic/google/resources/release.py

Not all Firebase App Distribution releases have release notes attached to them. This causes related `firebase-app-distribution` actions to fail with the following exception:
```python
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 212, in invoke_cli
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 168, in _invoke_action
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 463, in wrapper
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/tools/firebase_app_d …
```

Bugfix: Do not require release notes for Firebase releases

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/provisioning/bundle_ids.py
src/codemagic/apple/resources/enums.py
src/codemagic/utilities/decorators.py
tests/apple/app_store_connect/provisioning/test_bundle_ids.py
tests/utilities/decorators/test_deprecated.py

Add decorator `deprecated` to mark functions and methods as obsolete in a uniform way.
Use this new decorator to replace inlined warnings in `ProfileType.devices_allowed`. Also mark `BundleIds.list_capabilility_ids` as deprecated, and create new method without typo in the name to replace that. Original method is persisted as a mere proxy for now.
- None
An example use-case of how this works can be seen from this mocked action:

Feature: Add decorator to mark functions as deprecated

---

CHANGELOG.md
docs/app-store-connect/README.md
docs/app-store-connect/list-devices.md
docs/app-store-connect/register-device.md
poetry.toml
pyproject.toml
src/codemagic/__version__.py
src/codemagic/cli/argument/typed_cli_argument.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/_xcode_project/arguments.py
src/codemagic/tools/android_keystore/argument_types.py
src/codemagic/tools/app_store_connect.py
src/codemagic/tools/firebase_app_distribution/argument_types.py

1. Update `app-store-connect register-device` to accept now accepts multiple UDIDs from a file or an environment variable as a source.
2. Introduce `--ignore-registration-errors` flag for `app-store-connect register-device` to continue registering devices despite errors.
3. Introduce short flags for `app-store-connect register-device`:
- `-n` flag for the device name,
- `-u` flag for the UDIDs.
<details>
<summary>Demonstration of the command and its output</summary>
```
00000000-000000000000001E
00000000-000000000000002E
00000000-000000000000003X
```
UDIDs in file:
1. Valid UDID, but the device is present. 
2. Valid UDID, the device doesn't yet exists and will be registered
3. Invalid UDID
```shell
app-store-connect register-device -n iPhone -u @file:Device\ UDIDs.txt …
```

Feature: register-device supports multiple UDIDs

---

.github/workflows/run-checks.yml
CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py

When running `app-store-connect get-certificate <certificate-id>` without `--certificate-key` argument then the action crashes with the following error:
```python
File "/usr/local/lib/python3.11/site-packages/codemagic/cli/cli_app.py", line 206, in invoke_cli
File "/usr/local/lib/python3.11/site-packages/codemagic/cli/cli_app.py", line 163, in _invoke_action
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/codemagic/cli/cli_app.py", line 458, in wrapper
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/codemagic/tools/app_store_connect.py", line 706, in get_certificate
assert private_key is not None …
```

Fix running `app-store-connect get-certificate` without certificate private key

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/application_package/ipa.py

Creating `Ipa` instances from large archives (4+GB) results in the following exception:
```python
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/models/application_package/ipa.py", line 23, in _validate_package
return bool(self.info_plist)
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/models/application_package/ipa.py", line 83, in info_plist
return self._get_info_plist()
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/models/application_package/ipa.py", line 77, in _get_info_plist
info_plist_contents = self._get_app_file_contents("Info.plist")
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/models/application_package/ …
```

Add support for large iOS application packages

---

CHANGELOG.md
docs/google-play/README.md
docs/google-play/get-latest-build-number.md
docs/google-play/tracks.md
docs/google-play/tracks/get.md
docs/google-play/tracks/list.md
docs/google-play/tracks/promote-release.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/cli/argument/common_argument_types.py
src/codemagic/google_play/api_client.py
src/codemagic/google_play/api_error.py
src/codemagic/google_play/resources/__init__.py
src/codemagic/google_play/resources/resource.py
src/codemagic/google_play/resources/track.py
src/codemagic/tools/google_play/action_groups/tracks_action_group.py
src/codemagic/tools/google_play/arguments.py
tests/cli/argument/common_argument_types/test_bounded_number.py
tests/google_play/resources/test_resource_print.py

In Google Play is is possible to promote a release from one release track to another. For example, one might initially publish the release binary (`aab` or `apk`) to be internally tested. Once is tested, then the same version could be promoted to either some broader test track like or directly to production.
This PR introduces new action `google-play tracks promote-release` to promote release from one track to another.
**Example usage:**
```shell
$ google-play tracks promote-release --package-name "io.codemagic.capybara" --source-track "internal" --target-track "alpha" --release-status "draft"
Promote release 1.0.2 (437) from track "internal" to track "alpha"
Successfully completed release promotion to track alpha
Track: alpha
Releases: [
Status: draft
Name: 1.0.2
Version codes: [
437
]
] …
```

Google Play release promotion

---

CHANGELOG.md
docs/app-store-connect/get-latest-app-store-build-number.md
docs/app-store-connect/get-latest-build-number.md
docs/app-store-connect/get-latest-testflight-build-number.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/__init__.py
src/codemagic/apple/resources/build.py
src/codemagic/tools/_app_store_connect/arguments.py
src/codemagic/tools/_app_store_connect/resource_printer.py
src/codemagic/tools/app_store_connect.py

**Resolves #344.**
Add an option `--include-version` to output build's version name together with build number when querying latest build number with actions
- `app-store-connect get-latest-build-number`,
- `app-store-connect get-latest-app-store-build-number`,
- `app-store-connect get-latest-testflight-build-number`.
<details>
<summary>Example usage</summary>
</details>
If `--include-version` is not specified then the actions still outputs just the build number without any additional fields, even if `--json` is given. That is, constructing next build number using something like
```shell
CURRENT_LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID")
NEXT_BUILD_NUMBER=$(($CURRENT_LATEST_BUILD_NUMBER + 1))
```
will still work as before.
<details> …

Add option to output version string when querying latest build number from App Store Connect

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/app_store_connect/builds/builds.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py

**Resolves #346.**
PR #340 added support to publish macOS applications to TestFlight and App Store using `app-store-connect publish`. To submit uploaded binary to either we first need to get the build reference in App Store Connect. The method which is responsible for build lookup only filtered the builds by application identifier and version, but it did not take application platform into account.
Consequently old(er) iOS build could have been found for a currently published macOS application (or vice versa) as long as both shared the same version string and build number.
To avoid such situations also filter the builds by platform and reverse order to have most recent uploads in the head of the returned builds list.

Fix `app-store-connect publish` build lookup

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/application_package/abstract_package.py
src/codemagic/models/application_package/ipa.py

Follow up to PR #342.
Extracting files from ipa files can fail with `Bad magic number for file header` error even if the binary is exceptionally large (>4GB).
Full stacktrace:
```python
[18:38:23 29-09-2023] WARNING cli_app.py:114 > Executing AppStoreConnect action publish failed unexpectedly. Detailed logs are available at "/var/folders/vs/tcrc5cns67zgynxt6fssjdg80000gn/T/codemagic-29-09-23.log". To see more details about the error, add `--verbose` command line option.
[18:38:23 29-09-2023] ERROR cli_app.py:116 > Exception traceback:
File "/Users/priit/nevercode/cli-tools/src/codemagic/models/application_package/ipa.py", line 25, in _validate_package
return bool(self.info_plist)
^^^^^^^^^^^^^^^
File …
```

Add support for large iOS application packages x2

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py

[Read Device Information](https://developer.apple.com/documentation/appstoreconnectapi/read_device_information) and [List Devices](https://developer.apple.com/documentation/appstoreconnectapi/list_devices) App Store Connect API endpoints can return [devices](https://developer.apple.com/documentation/appstoreconnectapi/device/attributes) whose `deviceClass` attribute value is `APPLE_VISION_PRO`.
As of now such a device class is not supported and causes issues when the device class info is used, such as
```python
[07:54:38 02-10-2023] ERROR cli_app.py:116 > Exception traceback:
File "/Users/builder/.pyenv/versions/3.8.13/lib/python3.8/site-packages/codemagic/cli/cli_app.py", line 206, in invoke_cli
File …
```

Bugfix: Support Apple Vision Pro device type

---

CHANGELOG.md
docs/app-store-connect/builds/submit-to-app-store.md
docs/app-store-connect/publish.md
src/codemagic/tools/_app_store_connect/arguments.py

From what I understand, is it not possible to cancel TestFlight submissions, right? I found the question "[Delete Beta App Review Submission via App Store Connect API](https://developer.apple.com/forums/thread/680143)" in the apple forum which asks this question. Still today, I can't find a delete option in the [API docs](https://developer.apple.com/documentation/appstoreconnectapi/prerelease_versions_and_beta_testers/beta_app_review_submissions).
When reading the docs for `app-store-connect publish` I thought it would also delete the previous TestFlight submissions when using the `--testflight` flag. I tried it out, but it didn't work (see [logs](https://github.com/SharezoneApp/sharezone-app/actions/runs/6248488396/job/16963390721)). Therefore, I clarified the docs about …

Add note that `--cancel-previous-submissions` does not work for TestFlight submissions

---

CHANGELOG.md
docs/app-store-connect/publish.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/_app_store_connect/actions/publish_action.py
src/codemagic/tools/_app_store_connect/arguments.py

**Resolves #350.**
Once a binary is uploaded to Apple using `app-store-connect publish` it can take quite some time for the corresponding build to appear in App Store Connect UI and API responses. Build reference is needed to automatically submit the freshly uploaded version to TestFlight or App Store right after publishing.
For now there is a fixed 10 minute timeout period to find the build after upload completes. Occasionally this does not suffice and consequently publishing as a whole fails.
Changes in this pull request introduce new command line option `--max-find-build-wait` which can be used to configure the duration of the waiting period before.

Add option to configure timeout for finding build from App Store Connect

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google_play/resources/track.py
tests/google_play/resources/test_track_resource.py

**Fixes #360**
There is a bug in `codemagic.google_play.resources.Release` initialization due to naive expectation in `__post_init__` method that release notes are always passed as lists of dictionaries like they come from Google Play API responses. It should also be possible to initialize the object in case the notes are given with their expected target type `List[LocalizedText]`.
One possible consequence of this is that duplicating release with notes fails with the following error:
```python
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/priit/.pyenv/versions/3.12.0/lib/python3.12/dataclasses.py:1579: in replace
return obj.__class__(**changes)
<string>:10: in __init__
???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Fix Google Play release promotion

---

.github/workflows/run-checks.yml
CHANGELOG.md

Update job declarations for GitHub Actions:
- add job to run tests with Python 3.12,
- use `actions/cache@v3` instead of `actions/cache@v1`,
- use `actions/setup-python@v4` instead of `actions/setup-python@v1`,
- use unique cache key per job.

Update GitHb Action CI jobs

---

.github/workflows/run-checks.yml

For quite some time already Python dependencies have been installed to `.venv` in CI jobs. GitHub Actions however cachede `~/.cache/pip`, which is of no use.

Update cache paths in GitHub Actions

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/code_sign_entitlements.py
src/codemagic/models/simulator/runtime.py
src/codemagic/models/xcode.py
src/codemagic/models/xcodebuild.py
tests/models/simulator/test_runtime.py
tests/models/test_certificate.py
tests/models/test_xcode.py

**Description**
[PEP-632](https://peps.python.org/pep-0632/) deprecated `distutils` module in Python 3.10, and starting from 3.12 it is not included in standard library any more.
CLI tools used `LooseVersion` from `distutils.version` for version number comparisons in number of places and now related imports are broken on Python 3.12 unless `distutils` is manually installed on the system.
To overcome that issue, use [PEP-440](https://peps.python.org/pep-0440/) compliant version handling layer from [`packaging`](https://packaging.pypa.io/en/latest/index.html) library by [PyPA](https://github.com/pypa):
```python
from packaging.version import Version
```
which, for our use-cases, is a drop-in replacement for `LooseVersion`.
**The changes induce backwards-incompatibility in two places for …

Remove `distutils.version.LooseVersion` usages

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/scripts/code_signing_manager.rb

Setting code signing settings for Xcode project with [`xcode-project use-profiles`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/xcode-project/use-profiles.md) does not override platform-specific provisioning profile assignations. For example, if my project file already contains entry such as
```
"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "Original Profile";
```
then running `xcode-project use-profile` just adds another `PROVISIONING_PROFILE_SPECIFIER` definition for the target:
```
PROVISIONING_PROFILE_SPECIFIER = "Another Profile";
```
which results in a conflicting provisioning code signing setup because both profiles are defined in the `project.pbxproj` file:
```
"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "Original Profile"; …
```

Fix setting provisioning profile specifiers for specific SDKs 

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google/resource_managers/mixins/acting_manager_mixin.py
src/codemagic/google/resource_managers/mixins/listing_manager_mixin.py
src/codemagic/tools/firebase_app_distribution/action_groups/releases_action_group.py

Firebase releases API has started to return empty respones to listing requests. Handle those by checking if the requested resource key is present in the response object instead of failing unexpectedly with `KeyError`.
**Example traceback:**
```python
[17:39:37 08-11-2023] INFO  acting_manager_mixin.py:42 > >>> GET https://firebaseappdistribution.googleapis.com/v1/projects/228333310124/apps/1:228333310124:ios:5e439e0d0231a788ac8f09/releases?orderBy=createTimeDesc&pageSize=1&alt=json None
[17:39:38 08-11-2023] INFO  acting_manager_mixin.py:47 > <<< {}
[17:39:38 08-11-2023] WARNING cli_app.py:121 > Executing "firebase-app-distribution get-latest-build-version" failed unexpectedly. Detailed logs are available at "/var/folders/wr/c44p23x10f302_kfbj32z0p80000gn/T/codemagic-08-11-23.log". To see …
```

Handle empty reponses from Google APIs for listing requests

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/keychain.py

It is possible to specify custom certificate paths or path patterns for action `keychain add-certificates` via CLI option `--certificate`. As this option accepts either path literals, or a glob patterns to match certificates, then relative reference `.` to current directory should also be an acceptable input. This however results in an error when globbing matches:
```python
>>> list(Path().glob('.'))
File "/Users/priit/development/nevercode/cli-tools/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-23-b1f87bcdf599>", line 1, in <cell line: 0>
list(Path().glob('.'))
File "/Users/priit/.pyenv/versions/3.12.0/lib/python3.12/pathlib.py", line …
```

Fix certificates globbing from relative paths for `keychain add-certificates`

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect.py

When running `app-store-connect` actions with private key that is not issued by App Store Connect (i.e. a valid PEM encoded private key that is not elliptic curve private key) then generating JSON web token for API requests fails and consequently the whole action fails unexpectedly:
```
$  APP_STORE_CONNECT_PRIVATE_KEY=@file:/tmp/invalid-key.pk app-store-connect apps get 1496105355
Get App 1496105355
Executing "app-store-connect apps get" failed unexpectedly. Detailed logs are available at "/var/folders/wr/c44p23x10f302_kfbj32z0p80000gn/T/codemagic-13-12-23.log". To see more details about the error, add "--verbose" command line option.
```
<details>
<summary>Output with <code>--verbose</code> option</summary>
```python
$APP_STORE_CONNECT_PRIVATE_KEY=@file:/tmp/invalid-key.pk …
```

Improve error handling for invalid App Store Connect API keys

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/xctests/__init__.py
src/codemagic/models/xctests/xcresulttool.py
src/codemagic/tools/xcode_project.py

It is possible that `xcresult` files that contain Xcode test results are corrupted (either by erroneous user interaction or Xcode generated them as such). For example if `Info.plist` is missing from the `xcresult` bundle, then applying any `xcrun xcresulttool` command to this bundle will fail and exits with error code 1.
For example:
```shell
$ xcrun xcresulttool get --format json --path /Users/priit/Library/Developer/Xcode/DerivedData/App-eyutjqzsoxkgpcbycmzihsrczspl/Logs/Test/Test-App-2024.01.10_09-07-42-+0000.xcresult
error: Info.plist at /Users/priit/Library/Developer/Xcode/DerivedData/App-eyutjqzsoxkgpcbycmzihsrczspl/Logs/Test/Test-App-2024.01.10_09-07-42-+0000.xcresult does not exist, the result bundle might be corrupted or the provided path is not a result bundle
```
As it is now, …

Handle `xcresulttool` failures

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/export_options.py
src/codemagic/tools/xcode_project.py
tests/models/test_export_options.py

New Xcode versions can introduce export options that are not defined in our `ExportOptions` class (for example `testFlightInternalTestingOnly` that was added some time ago, but for which we were lacking definition).
Also in general Xcode does not restrict usage of totally custom export options, and as such it makes little to no sense to be very strict about what keys are allowed in export options and what are not. This PR allows usage of export option keys that are not explicitly defined by the fields in `ExportOptions` class. Such fields are persisted when the object is updated and are included when the properly list is saved to disk.
- `xcode-project build-ipa`
<details>
<summary>Example log with warning about unknown export option</summary>
```shell
$ xcode-project …
```

Allow custom export options for `xcode-project build-ipa`

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/app.py

Listing applications now fails due to the deprecation of the following fields from App Store Connect [App](https://developer.apple.com/documentation/appstoreconnectapi/app/) data structure:
* `availableInNewTerritories` [attribute](https://developer.apple.com/documentation/appstoreconnectapi/app/attributes),
* `availableTerritories` and `prices` [relationships](https://developer.apple.com/documentation/appstoreconnectapi/app/relationships).
<details>
<summary>Exception traceback for deprecated attribute</summary>
```
[14:59:14] ERROR > Exception traceback:
File "/Users/artemii/codemagic/cli-tools/src/codemagic/cli/cli_app.py", line 243, in invoke_cli
File …
```

Fix: deprecate fields for App Store Connect App resource

---

.github/workflows/run-checks.yml
CHANGELOG.md

Use test matrix to define Python versions in GitHub actions test workflows instead of rewriting the whole workflow for every individual Python version.

CI: Use Python version test matrix for GH actions

---

CHANGELOG.md
src/codemagic/apple/resources/resource.py
tests/apple/resources/conftest.py
tests/apple/resources/mocks/app.json
tests/apple/resources/test_app_resource.py

It is possible that App Store Connect API returns resources with empty relationships. For example [List Apps](https://developer.apple.com/documentation/appstoreconnectapi/list_apps) endpoint can respond with a response where an app has [`ciProduct` relationship](https://developer.apple.com/documentation/appstoreconnectapi/app/relationships/ciproduct) defined as `{}` instead of `null` even though the schema suggests that relationships should always have at least `links` attribute defined. 
Such a response breaks data deserialization.
<details>
<summary>Example with stacktrace</summary>
```python
def test_empty_relationship():
>       App(
{
"type": "apps",
"id": "...",
"links": {...},
"attributes": {...},
"relationships": {
...,
"ciProduct": {},  # <-- empty relationship from App Store …
```

Bugfix: Ignore empty relationships on App Store Connect resources

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/app_store_version.py
tests/apple/resources/mocks/app_store_version.json
tests/apple/resources/test_app_store_version_resource.py

Appe removed `idfaDeclaration` attribute from App Store Version's relationships which caused model initialization to fail on our end due to `TypeError`. That in turn triggers number of failures when invoking CLI actions.
**Example stacktrace:**
```python
File "/Users/priit/.pyenv/versions/3.12.0/lib/python3.12/site-packages/codemagic/cli/cli_app.py", line 243, in invoke_cli
File "/Users/priit/.pyenv/versions/3.12.0/lib/python3.12/site-packages/codemagic/cli/cli_app.py", line 184, in _invoke_action
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/priit/.pyenv/versions/3.12.0/lib/python3.12/site-packages/codemagic/cli/action.py", line 83, in wrapper …
```

Bugfix: Remove `idfaDeclarations` field from `AppStoreVersion` model

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect/actions/publish_action.py

**Addresses #409**
Action `app-store-connect publish` requires that build needs to be submitted to TestFlight in order to add the build to beta groups. This is not necessary and actually builds can be assigned to beta groups regardless of their TestFlight submission status.
This PR removes that arbitrary limitation and makes it possible to add published build to beta groups without TestFlight submission.
**Examples**
- Publish ipa and just add it to beta groups:
```shell
app-store-connect publish --path app.ipa --beta-group "Group 1" "Group 2"
```
- Publish ipa and just submit it to TestFlight:
```shell
app-store-connect publish --path app.ipa --testflight --whats-new "..."
```
- Publish ipa and both add it to beta groups and submit it to TestFlight:
```shell
app-store-connect publish \ …
```

Do not require TestFlight submission when adding build to beta groups

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
src/codemagic/tools/app_store_connect/action_groups/certificates_action_group.py
src/codemagic/tools/app_store_connect/actions/fetch_signing_files_action.py
tests/apple/resources/enums/test_certificate_type.py

**Resolves #414** 
When creating Developer ID Application certificate in Apple Developer Portal, it is possible to select "G2 Sub-CA" for its profile type:
The certificate that is created will have type `DEVELOPER_ID_APPLICATION_G2`, which as of 04.07.24 is not documented as a possible [certificate type](https://developer.apple.com/documentation/appstoreconnectapi/certificatetype), but is used nonetheless.
Changes in this PR add bindings for this type and make it possible to use such certificates when requesting certificates for provisioning profiles of type `MAC_APP_DIRECT` and `MAC_CATALYST_APP_DIRECT`.
- `app-store-connect fetch-signing-files`
- `app-store-connect certificates list`

Add support for certificate type `DEVELOPER_ID_APPLICATION_G2`

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/xctests/xcresulttool.py
src/codemagic/tools/xcode_project.py
tests/models/xctests/test_xcresulttool.py

With Xcode 16.0 beta 3+ part of `xcresulttool` API that we use to parse Xcode test results has been deprecated:
```shell
% xcrun xcresulttool get object --help
OVERVIEW: Get Result Bundle Object. This subcommand is deprecated and will be removed in a future release, consider using `xcresulttool get test-report` instead.
USAGE: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
...
```
This causes `xcresulttool get object` calls with recent Xcode versions to exit with error and consequently some actions in `xcode-project` fail.
Apple has provided a quick workaround by providing `--legacy` flag that can be used to still use the old API even on more recent `xcresulttool` version. Changes on this PR make use of that flag when calling …

Fix using xcresulttool on Xcode 16.0 beta 3+

---

CHANGELOG.md
docs/app-store-connect/app-store-versions/localizations.md
docs/app-store-connect/beta-build-localizations/create.md
docs/app-store-connect/beta-build-localizations/list.md
docs/app-store-connect/builds/add-beta-test-info.md
docs/app-store-connect/builds/submit-to-app-store.md
docs/app-store-connect/publish.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/apple/resources/enums.py
src/codemagic/models/enums.py
tests/models/enums/test_resource_enum.py

Update `codemagic.apple.resources.enums.Locale` to match the [locales supported by Apple](https://developer.apple.com/documentation/appstoreconnectapi/app_store/app_metadata/app_info_localizations/managing_metadata_in_your_app_by_using_locale_shortcodes).
For now some locales are missing from our definitions and this can cause troubles when working with any resource that relies on locale value.
- `app-store-connect app-store-versions localizations`,
- `app-store-connect beta-build-localizations create`,
- `app-store-connect beta-build-localizations list`,
- `app-store-connect builds add-beta-test-info`,
- `app-store-connect builds submit-to-app-store`,
- `app-store-connect publish`.

Add missing App Store Connect locales

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/certificate_p12_exporter.py

**Fixes #419**
PR #411 introduced a regression when exporting Apple code signing certificates to PKCS#12 containers.
Just checking `openssl version` to decide whether `-noenc` option is supported for PKCS#12 export can yield misleading results as there are different implementations whose versioning schemes and APIs do not agree with each other.
For example OpenSSL 3.0.0+ has deprecated `-nodes` in favor of `-noenc`, while LibreSSL 3.3.6. still uses `-nodes` and doesn't even recognize `-noenc`.
To choose correct flag to skip private key encryption for `openssl pkcs12`, just check the help message and see if it contains `-noenc`, otherwise use the legacy `-nodes`.
**Updated actions**:
- `app-store-connect certificates create`,
- `app-store-connect certificates get`,
- `app-store-connect …

Fix certificates exporting with LibreSSL

---

CHANGELOG.md
codemagic.yaml
pyproject.toml
src/codemagic/__version__.py

By default PyPI imposes 10GB limit to total uploaded artifact size. This package already hit this limit which caused the release pipeline to fail.
Reduce PyPI artifact size by not uploading source tarballs there as those are readily available from GitHub anyway.

Do not publish source distributions to PyPI

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/xctests/converter.py
src/codemagic/models/xctests/xcresult/xcode_16_xcresult.py
tests/models/xctests/converter/test_xcode_16_converter.py

**Fixes #432**
This PR fixes a bug from #431 which happens when parsing test results from XCResult using Xcode 16.0+ and any of the test cases ran longer than a minute.
Updated actions:
- `xcode-project run-tests`
- `xcode-project test-summary`
- `xcode-project junit-test-results`

Fix XCResult testcase duration parsing

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/altool/altool.py
tests/models/altool/test_altool_retrying.py

Application loader tool can exit unexpectedly with return code `-5` or `-11` when running `altool --upload-app` without any error or warning messages in log output even though the application binary and authentication information are both valid. Subsequent `altool --upload-app` calls using the same binary can complete normally.
Handle such unexpected exits by enabling retrying for those exit codes.

Retry `altool --upload-app` on return codes `-5` and `-11`

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect/actions/fetch_signing_files_action.py

App Store Connect [list bundle IDs](https://developer.apple.com/documentation/appstoreconnectapi/list_bundle_ids) API endpoint requires that parameter `filter[identifier]` is not an empty string. Currently this is not enforced by `app-store-connect fetch-signing-files` and can result in weird error message that does not translate well into executed CLI command.
Apply runtime parameter validation and raise an argument error in case empty identifier is used:
```shell
% app-store-connect fetch-signing-files ''
usage: app-store-connect [-h] [--log-stream {stderr,stdout}] [--no-color] [--version] [-s] [-v]
{app-store-version-localizations,app-store-version-phased-releases,app-store-version-submissions,app-store-versions,apps,beta-app-review-submissions,beta-build-localizations,beta-groups,build …
```

Add graceful handling for missing bundle ID identifer on `app-store-connect fetch-signing-files` action

---

CHANGELOG.md
src/codemagic/apple/resources/app.py

Occasionally App Store Connect [list apps](https://developer.apple.com/documentation/appstoreconnectapi/list_apps) and [read app information](https://developer.apple.com/documentation/appstoreconnectapi/read_app_information) endpoints respond with payloads where included [application resources](https://developer.apple.com/documentation/appstoreconnectapi/app) are lacking `preOrder` relationship, which is currently declared as mandatory.
That causes `App` object initialization to fail:
```python
File "/usr/local/lib/python3.11/site-packages/codemagic/cli/action.py", line 83, in wrapper
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/codemagic/tools/app_store_connect/action_groups/beta_groups_action_group.py", line 33, in …
```

Make deprecated relations on `App` resource optional

---

CHANGELOG.md
doc.py
docs/app-store-connect/app-store-version-localizations/README.md
docs/app-store-connect/app-store-version-phased-releases/README.md
docs/app-store-connect/app-store-version-submissions/README.md
docs/app-store-connect/app-store-versions/README.md
docs/app-store-connect/apps/README.md
docs/app-store-connect/beta-app-review-submissions/README.md
docs/app-store-connect/beta-build-localizations/README.md
docs/app-store-connect/beta-groups/README.md
docs/app-store-connect/builds/README.md
docs/app-store-connect/bundle-ids/README.md
docs/app-store-connect/certificates/README.md
docs/app-store-connect/devices/README.md
docs/app-store-connect/profiles/README.md
docs/app-store-connect/review-submission-items/README.md
docs/app-store-connect/review-submissions/README.md
docs/firebase-app-distribution/releases/README.md
docs/google-play/tracks/README.md

Duplicate action group documentation in respective action group documentation directory in `README.md`.

Duplicate readme pages for action groups

---

doc.py
docs/app-store-connect/app-store-version-localizations/README.md
docs/app-store-connect/app-store-version-phased-releases/README.md
docs/app-store-connect/app-store-version-submissions/README.md
docs/app-store-connect/app-store-versions/README.md
docs/app-store-connect/apps/README.md
docs/app-store-connect/beta-app-review-submissions/README.md
docs/app-store-connect/beta-build-localizations/README.md
docs/app-store-connect/beta-groups/README.md
docs/app-store-connect/builds/README.md
docs/app-store-connect/bundle-ids/README.md
docs/app-store-connect/certificates/README.md
docs/app-store-connect/devices/README.md
docs/app-store-connect/profiles/README.md
docs/app-store-connect/review-submission-items/README.md
docs/app-store-connect/review-submissions/README.md
docs/firebase-app-distribution/releases/README.md
docs/google-play/tracks/README.md

Reamde files that were added in #444 had broken links to action documentation pages. This PR fixes them.

Fix action documentation links in action group readme tables

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/shell_tools/bundletool.py

Fix a regression from #446 that caused `android-app-bundle build-apks` and  `android-app-bundle build-universal-apk` actions to fail unexpectedly if keystore arguments were provided.
Keystore and key password arguments were passed to bundletool using invalid flags (originally in version 0.56.0 like [this](https://github.com/codemagic-ci-cd/cli-tools/blob/v0.56.0/src/codemagic/tools/android_app_bundle.py#L477-L484) and in 0.57.0 as [this](https://github.com/codemagic-ci-cd/cli-tools/blob/v0.57.0/src/codemagic/shell_tools/bundletool.py#L129-L138)).

Fix `android-app-bundle build-apks` and  `android-app-bundle build-universal-apk` actions

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/codemagic/__version__.py
src/codemagic/models/application_package/apk_package.py
tests/models/application_package/test_apk_package.py

Androguard dependency was added in #446. It is a rather heavy Python package which has many dependencies on its own, some of which have native code that has to be compiled. All this has negative impact on initial `codemagic-cli-tools` package installation time, which is especially evident in CI environments.
Androguard is required only for handful of actions:
- `google-play apks upload`,
- `google-play apks publish`,
- `google-play internal-app-sharing upload-apk`.
As publishing APKs to Google Play has been deprecated for many years already and it isn't even possible to upload APKs for apps that were created after 2021, then those actions are rarely used.
Instead of having a general penalty for all users, install Androguard only when it is needed and not present on the system.

Make Androguard dependency optional for initial installation

---

CHANGELOG.md
src/codemagic/__version__.py
src/codemagic/shell_tools/jarsigner.py

Pass correct `keystore_password` to `jarsigner` which was introduced in https://github.com/codemagic-ci-cd/cli-tools/pull/446

Bugfix: Pass correct keystore_password to jarsigner

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect/actions/publish_action.py
tests/tools/app_store_connect/actions/publish_action/test_app_store_submission.py

**Fixes #451.**
Fix issues related to submitting apps to App Store using action `app-store-connect publish` with `--app-store` option.
**Issue description**
AppStoreConnect.publish first uploads the binaries using the private method _process_application_after_upload. If that succeeds, post-processing is carried out by another private method, _process_application_after_upload, which invokes additional actions based on the supplied CLI options.
The arguments for these actions are gathered using special dataclasses that mimic the signatures of the actions. However, the actions themselves were invoked via the Python API using dictionary unpacking, where arguments were passed as `**dataclasses.asdict(action_args_dataclass)`. This conversion to a dictionary resulted in the loss of type …

Fix App Store submission options for `app-store-connect publish`

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/tools/app_store_connect/actions/submit_to_app_store_action.py
tests/tools/app_store_connect/actions/test_submit_to_app_store_action.py

Submitting macOS applications to App Store review is broken in case the submission is invoked from Python API by specifying platform info using `AppStoreVersionInfo` instead of the `platform` argument. That is, running
```python
AppStoreConnect(...).submit_to_app_store(
"build-id",
app_store_version_info=AppStoreVersionInfo(
platform=Platform.MAC_OS,
...,
),
...,  # platform uses default value
)
```
will end up using default platform type `Platform.IOS` for the review submission instead of the one that is given in version info. This causes a conflict that fails the App Store submission.
The issue is resolved by altering private `_submit_to_app_store` method to only use platform from the `app_store_version_info` where correct platform type is given.
- …

Fix version info resolving when submitting app to App Store

---

CHANGELOG.md
doc.py
pyproject.toml
src/codemagic/__version__.py
src/codemagic/cli/action.py
src/codemagic/cli/argument/action_callable.py
src/codemagic/cli/argument/argument_parser_builder.py
src/codemagic/cli/cli_app.py
src/codemagic/cli/cli_help_formatter.py
src/codemagic/models/application_package/apk_package.py
src/codemagic/tools/codemagic_cli_tools.py
src/codemagic/tools/google_play/action_groups/apks_action_group.py
src/codemagic/utilities/decorators.py
tests/utilities/decorators/test_run_once.py

There are couple of problems with [androguard](https://github.com/androguard/androguard) dependency and its usage.
First, updating `androguard` log level multiple times causes `ValueError`s because `androguard.util.set_log` method uses hardcoded ID value to remove `logger`'s handler, but new handler is added gets another ID. 
Changes here ensure that log level is updated only once.
<details>
<summary>Stacktrace</summary>
```python
File "/home/builder/builder/.venv/lib/python3.10/site-packages/codemagic/models/application_package/apk_package.py", line 63, in _validate_package
_ = self._apk
File "/home/builder/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/functools.py", line 981, in __get__
val = self.func(instance)
File …
```

Androguard improvements

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google/services/google_play/apks_service.py
src/codemagic/google/services/google_play/bundles_service.py
src/codemagic/google/services/google_play/deobfuscation_files_service.py
src/codemagic/google/services/google_play/expansion_files_service.py
src/codemagic/google/services/google_play/internal_app_sharing_artifacts_service.py
src/codemagic/google/services/resource_service.py

HTTP requests to Google APIs often time out. Example stacktrace:
```python
File "/home/builder/.local/lib/python3.10/site-packages/codemagic/cli/cli_app.py", line 252, in invoke_cli
File "/home/builder/.local/lib/python3.10/site-packages/codemagic/cli/cli_app.py", line 193, in _invoke_action
File "/home/builder/.local/lib/python3.10/site-packages/codemagic/cli/action.py", line 83, in wrapper
File "/home/builder/.local/lib/python3.10/site-packages/codemagic/tools/google_play/action_groups/tracks_action_group.py", line 46, in get_track
track = self.client.tracks.get(package_name, track_name, edit.id)
File …
```

Use retrying by default for Google API requests

---

CHANGELOG.md
src/codemagic/mixins/str_converter.py

Subprocess output can be encoded using [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) on Windows. This causes problems when converting `bytes` to `str` and only allowing UTF-8. This PR adds an exemption on Windows to also allow Windows-1252 encoding when the program is also running on Windows.
Example stacktrace:
```python
File "codemagic\models\application_package\aab_package.py", line 156, in get_summary
File "codemagic\models\application_package\aab_package.py", line 129, in get_app_name
File "functools.py", line 981, in __get__
File "codemagic\models\application_package\aab_package.py", line 67, in _resources
File "codemagic\shell_tools\bundletool.py", line 83, in dump
File "codemagic\shell_tools\shell_tool.py", line 51, in _get_stdout …
```

Fix converting bytes to strings on Windows

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google/services/google_play/apks_service.py

Unless mime type is explicitly specified in request parameters, `googleapiclient.discovery` tries to [resolve it by itself](https://github.com/googleapis/google-api-python-client/blob/607bd3d5168f0902632f6a75671d2b3d865b28d9/googleapiclient/discovery.py#L1189-L1196) using [`mimetypes.guess_type`](https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type). On Windows, and any other platform for which the default mime types mapping is missing entry for `.apk` files, this causes the upload request to fail with `UnknownFileType` error.
<details>
<summary>Stacktrace</summary>
```python
File "C:\Users\builder\AppData\Roaming\uv\tools\codemagic-cli-tools\Lib\site-packages\codemagic\cli\cli_app.py", line 252, in invoke_cli …
```

Fix uploading APKs to Goole Play on Windows

---

docs/app-store-connect/app-store-versions/localizations.md
docs/app-store-connect/beta-build-localizations/create.md
docs/app-store-connect/beta-build-localizations/list.md
docs/app-store-connect/builds/add-beta-test-info.md
docs/app-store-connect/builds/submit-to-app-store.md
docs/app-store-connect/publish.md
src/codemagic/apple/resources/enums.py

Add missing App Store Connect locale definition for Vietnamese (https://developer.apple.com/documentation/appstoreconnectapi/managing-metadata-in-your-app-by-using-locale-shortcodes)
- `app-store-connect app-store-versions localizations`
- `app-store-connect beta-build-localizations create`
- `app-store-connect beta-build-localizations list`
- `app-store-connect builds add-beta-test-info`
- `app-store-connect builds submit-to-app-store`

Add Locale Vietnamese in App Store Connect API enums

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google/resources/firebase/release.py
src/codemagic/google/resources/resource.py
src/codemagic/google/services/firebase/releases_service.py
tests/google/resources/firebase/test_release.py
tests/google/resources/mocks/firebase_release.json
tests/google/resources/test_resource.py

**Fixes #472.**
[Firebase releases API] started to include undocumented fields `updateTime` and `expireTime` in response payload. Those fields are not mapped to Python attributes and cause the program to crash:
```python
11:31:43 priit@marmot ~ firebase-app-distribution get-latest-build-version \
--app-id "1:146661841143:android:a8d456e0c8b5e71bd11bf2" \
--project-number "146661841143" \
--verbose
[11:31:45] WARNING > Executing "firebase-app-distribution get-latest-build-version" failed unexpectedly. Detailed logs are available at "/var/folders/wr/c44p23x10f302_kfbj32z0p80000gn/T/codemagic-25-08-25.log".
[11:31:45] ERROR > Exception traceback:
File "/Users/priit/.local/share/uv/tools/codemagic-cli-tools/lib/python3.13/site-packages/codemagic/cli/cli_app.p …
```

Fix Firebase Release initialization from API response data

---

CHANGELOG.md
pyproject.toml
src/codemagic/__version__.py
src/codemagic/google/resources/firebase/release.py
tests/google/resources/firebase/test_release.py

When building an Android application using a `build.gradle` file which not specify `versionCode` and `versionName` then the produced `apk` / `aab` will have `null` and `""` values for `versionCode` and `versionName` respectively.
```shell
$ uvx androguard apkid app/build/intermediates/apk/debug/app-debug.apk
{
"app/build/intermediates/apk/debug/app-debug.apk": [
"io.codemagic.cli_tools_firebase",
null,
""
]
}
```
When such an app is uploaded to Firebase App Distribution, then its JSON representation in responses for [releases](https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.apps.releases) requests is as follows:
```json
{
"name": "projects/146661841143/apps/1:146661841143:android:a8d456e0c8b5e71bd11bf2/releases/6gob495k4ackg",
"releaseNotes": {
"text": …
```

Allow Firebase release not to have `displayVersion` attribute
